/**
 * Cline bridge — `.clinerules/hooks/<NativeEvent>` per-event scripts.
 *
 * Phase 7.6 (docs/contracts/hook-architecture-v1.md): Cline project
 * hooks are individual executable scripts named exactly after the hook
 * (no extension). One script per (ac_event, native_event) binding.
 *
 * The script reads stdin (Cline's payload), forwards it into
 * `./agent-config dispatch:hook`, then emits the empty JSON envelope
 * Cline expects (`{}` = no cancel, no context modification). `cd
 * "$WORKSPACE_ROOT"` is intentional — guards against cline#8073-class
 * shifts in cwd handling.
 *
 * Mirror of `scripts/install.py:ensure_cline_bridge` (lines 1181–1254).
 */

import { join, resolve } from 'node:path';

import { type AcEvent, type BridgeBuilder, type ScriptBridgeOutput } from './types.js';

export const CLINE_BINDINGS: ReadonlyArray<readonly [AcEvent, string]> = [
    ['session_start',      'TaskStart'],
    ['session_start',      'TaskResume'],
    ['session_end',        'TaskComplete'],
    ['stop',               'TaskCancel'],
    ['user_prompt_submit', 'UserPromptSubmit'],
    ['post_tool_use',      'PostToolUse'],
];

/**
 * POSIX shell single-quote: wraps the value in `'…'` and escapes any
 * internal single quotes via the standard `'\''` sequence. Matches
 * Python's `shlex.quote` for the inputs the bridge actually uses
 * (filesystem paths).
 */
export function shellQuote(value: string): string {
    return `'${value.replace(/'/g, "'\\''")}'`;
}

function buildBody(acEvent: AcEvent, nativeEvent: string, workspaceQuoted: string): string {
    return `#!/usr/bin/env bash
# Generated by event4u/agent-config — DO NOT EDIT.
# Project-scope Cline hook for ${nativeEvent} → agent-config ${acEvent}.
# Phase 7.6 (docs/contracts/hook-architecture-v1.md).
set -u
EVENT_DATA="$(cat)"
WORKSPACE_ROOT=${workspaceQuoted}
cd "$WORKSPACE_ROOT" 2>/dev/null || { printf '%s\\n' '{}'; exit 0; }
if [ ! -x ./agent-config ]; then
    printf '%s\\n' '{}'
    exit 0
fi
printf '%s' "$EVENT_DATA" \\
    | ./agent-config dispatch:hook \\
        --platform cline \\
        --event ${acEvent} \\
        --native-event ${nativeEvent} \\
        >/dev/null 2>&1 || true
printf '%s\\n' '{}'
exit 0
`;
}

/** Builder for the Cline project-scope bridge (one script per binding). */
export const buildClineBridge: BridgeBuilder = (ctx): readonly ScriptBridgeOutput[] => {
    const workspaceQuoted = shellQuote(resolve(ctx.projectRoot));
    return CLINE_BINDINGS.map(([acEvent, native]) => ({
        kind: 'script' as const,
        toolId: 'cline',
        target: join(ctx.projectRoot, '.clinerules', 'hooks', native),
        content: buildBody(acEvent, native, workspaceQuoted),
        mode: 0o755,
        label: `.clinerules/hooks/${native}`,
    }));
};
