#!/usr/bin/env tsx
/**
 * Generate docs/proof.md — the public, self-verifying trust surface.
 *
 * Market-readiness roadmap Track B / B4. Renders, from real sources, the three
 * proofs a skeptic can check themselves:
 *   1. Every markered public claim binds to a resolvable evidence pointer
 *      (rendered from docs/CLAIMS.md — reuses the check_claims ledger loader).
 *   2. Honest-null results are published, not hidden (pointer to docs/benchmark.md).
 *   3. A "verify it yourself" block — the exact commands that reproduce 1 + 2 on
 *      a fresh checkout.
 *
 * **Generated, never hand-maintained** — drift-checked in CI via `--check`, the
 * same discipline as generate_capabilities_index / generate_cookbook. Output is
 * deterministic (sorted, no timestamp) so `--check` is stable. A proof page that
 * could drift from its sources would undermine the very claim it makes.
 *
 * Usage:
 *     ./scripts-run src/scripts/build_proof            # (re)write docs/proof.md
 *     ./scripts-run src/scripts/build_proof --check    # exit 2 if stale
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { REPO, LEDGER_REL, load_ledger, pointer_unresolved } from './check_claims.js';
import { collectSkillGaps } from './check_skill_gaps.js';

const _FILE = fileURLToPath(import.meta.url);
const OUT_REL = 'docs/proof.md';
const BENCH_REL = 'docs/benchmark.md';

class ExitCode extends Error {
    code: number;
    constructor(code: number) {
        super(`exit ${code}`);
        this.code = code;
    }
}

function render(): string {
    const ledger = load_ledger();
    const entries = [...ledger.values()].sort((a, b) => a.id.localeCompare(b.id));
    const backed = entries.filter((e) => e.status === 'backed');
    const unbacked = entries.filter((e) => e.status === 'unbacked');

    const L: string[] = [];
    L.push('<!-- GENERATED by src/scripts/build_proof.ts — do NOT hand-edit.');
    L.push('     Drift-checked in CI (`task build-proof-check`). Regenerate with');
    L.push('     `./scripts-run src/scripts/build_proof` after editing docs/CLAIMS.md. -->');
    L.push('');
    L.push('# Proof — verify our claims yourself');
    L.push('');
    L.push('We sell falsifiability, so the selling is machine-checked. Every');
    L.push('public claim binds to resolvable evidence; a skeptic can reproduce');
    L.push('every check below on a fresh checkout. This page is itself generated');
    L.push('from those sources and fails CI if it drifts.');
    L.push('');
    L.push('## 1. Every public claim binds to evidence');
    L.push('');
    L.push(`Rendered from [\`${LEDGER_REL}\`](CLAIMS.md). A \`<!-- claim:ID -->\` marker in`);
    L.push('README/docs must resolve to a `backed` entry here with a resolving');
    L.push('evidence pointer, or `task check-claims` fails the build.');
    L.push('');
    L.push('| Claim | Kind | Evidence | Resolves |');
    L.push('|---|---|---|---|');
    for (const e of backed) {
        const un = pointer_unresolved(e.evidence);
        const resolves = un ? `❌ ${un}` : '✅';
        const claim = e.claim.replace(/\|/g, '\\|');
        const evidence = e.evidence.replace(/\|/g, '\\|');
        L.push(`| ${claim} | ${e.kind} | \`${evidence}\` | ${resolves} |`);
    }
    L.push('');
    L.push(`**${backed.length} backed claim(s)** — all evidence pointers resolve in CI.`);
    if (unbacked.length > 0) {
        L.push('');
        L.push(`We also publish our **debt**: ${unbacked.length} claim(s) are logged as`);
        L.push('`unbacked` inventory in the ledger — not yet bound, and therefore not');
        L.push('allowed to carry a marker in public prose. Hiding them would be the');
        L.push('opposite of the point.');
    }
    L.push('');
    L.push('## 2. We publish honest nulls');
    L.push('');
    if (fs.existsSync(path.join(REPO, BENCH_REL))) {
        L.push(`Benchmark results — **including the runs where the package changed nothing** —`);
        L.push(`live in [\`${BENCH_REL}\`](benchmark.md). We do not delete a measured null to`);
        L.push('make a number look better; the null is the evidence of honesty.');
    } else {
        L.push('Benchmark results are published under `docs/` including measured nulls.');
    }
    L.push('');
    L.push('## 3. Known limits (published, witness-tested)');
    L.push('');
    const skillGaps = collectSkillGaps();
    if (skillGaps.length === 0) {
        L.push('No skill has logged a known-limit `gaps:` entry yet. When one does, it');
        L.push('appears here with a witness test that reproduces the limitation — the');
        L.push('transparency surface a headline-benchmark structurally cannot ship.');
    } else {
        L.push('Each limitation below is stated by the skill itself and carries a witness');
        L.push('test that reproduces it. If the limitation is ever fixed, its witness goes');
        L.push('red — so a "Known limit" can never quietly become false.');
        L.push('');
        L.push('| skill | known limit | witness |');
        L.push('|---|---|---|');
        for (const sg of skillGaps) {
            for (const g of sg.gaps) {
                const desc = g.description.replace(/\|/g, '\\|');
                L.push(`| \`${sg.skill}\` | ${desc} | [\`${g.witness}\`](../${g.witness}) |`);
            }
        }
    }
    L.push('');
    L.push('## 4. Verify it yourself');
    L.push('');
    L.push('On a fresh checkout, reproduce the claims above:');
    L.push('');
    L.push('```bash');
    L.push('task check-claims   # every markered public claim binds to resolvable evidence');
    L.push('task check-refs     # no broken internal references');
    L.push('task check-skill-gaps    # every logged known-limit cites a real witness test');
    L.push('task build-proof-check   # this page is in sync with its sources');
    L.push('```');
    L.push('');
    L.push('If a claim ever loses its binding, or this page drifts from the ledger,');
    L.push('CI goes red. Reproducibility is the proof.');
    L.push('');
    return L.join('\n');
}

function main(argv: string[] = process.argv.slice(2)): number {
    const check = argv.includes('--check');
    if (argv.includes('-h') || argv.includes('--help')) {
        process.stdout.write('usage: build_proof [--check]\n');
        return 0;
    }
    const out = render();
    const outPath = path.join(REPO, OUT_REL);
    if (check) {
        const current = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : '';
        if (current !== out) {
            process.stderr.write(
                `❌  build_proof: ${OUT_REL} is stale. Run './scripts-run src/scripts/build_proof' and commit.\n`,
            );
            return 2;
        }
        process.stdout.write(`✅  build_proof: ${OUT_REL} in sync.\n`);
        return 0;
    }
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, out);
    process.stdout.write(`✅  build_proof: wrote ${OUT_REL}.\n`);
    return 0;
}

function _isCliEntry(): boolean {
    const a = process.argv[1];
    if (!a) return false;
    if (a === _FILE || pathToFileURL(path.resolve(a)).href === import.meta.url) return true;
    try {
        return fs.realpathSync(a) === fs.realpathSync(_FILE);
    } catch {
        return false;
    }
}
if (_isCliEntry()) {
    try {
        process.exit(main());
    } catch (exc) {
        if (exc instanceof ExitCode) process.exit(exc.code);
        throw exc;
    }
}

export { render, main, OUT_REL };
