#!/usr/bin/env -S npx tsx
/**
 * Gate — how many rule tokens does a session actually RECEIVE?
 *
 * P1.2 of `road-to-rule-delivery-integrity`. Claude Code loads
 * `~/.claude/rules/` and `<project>/.claude/rules/` **both**, user layer first,
 * with no dedup between them (host contract, quoted with citations in
 * `agents/evidence/analysis/claude-code-rules-dir-contract.md`). So the number
 * that matters is not what one tree contains — it is the sum of what arrives.
 *
 * Measured 2026-08-08 on a maintainer machine, exact BPE: **176,354 tokens
 * standing, 74,137 of them (42%) the same 91 rules twice.** Full six-topology
 * accounting: `agents/evidence/analysis/standing-rule-delivery-topologies.md`.
 *
 * Three deliberate properties:
 *
 * 1. **Measure what arrived, not what was projected.** Where an
 *    `InstructionsLoaded` record exists (the host logs which instruction files
 *    loaded, when, and why) the gate reads it and the filesystem sum becomes a
 *    cross-check. Where it does not, the filesystem sum stands alone. The gate
 *    always NAMES which input it used — a filesystem-only sum cannot see a rule
 *    that is projected but never loaded, nor one that loads from a layer nobody
 *    projected, and the second of those is the defect itself.
 * 2. **`assertScanned` posture.** Zero rule files is exit 3, not green. This
 *    repo has shipped gates that scanned an emptied tree and certified coverage
 *    that did not exist; the posture is the recorded fix, not boilerplate.
 * 3. **The ceiling cannot be raised silently.** `cap_raise_reason` in
 *    `src/config/budgets.yml` must be a real sentence naming which rule added
 *    the tokens. A placeholder fails the gate.
 *
 * Exit codes: `0` under cap · `1` over cap or an unstated cap raise · `2` usage
 * error · `3` dead scan scope.
 *
 * ## This is deliberately NOT a CI gate
 *
 * Both inputs are machine-local by construction. `.claude/rules/` is gitignored
 * (`.gitignore:123` — it is generated by `task sync` / `task generate-tools`),
 * and no CI workflow performs a user-scope install, so on a fresh runner
 * **neither** layer exists. Wired into `ci` it would either red on a dead scope
 * or, with the empty case allowed, sit permanently green while certifying a
 * property it cannot observe — the exact failure `src/config/gate-coverage.yml`
 * was written to end. It is therefore registered as a local / doctor-surface
 * check and is absent from `gate-coverage.yml`, whose contract is CI-identical
 * invocation.
 *
 * What that costs, stated plainly: the duplicate-delivery defect is not
 * mechanically caught for anyone who never runs this locally. The enforced layer
 * is the installer gate (`install.ts::_gate_rule_layer_overlap`), which refuses
 * to CREATE the doubled state; this script measures a state that already exists.
 * Making the measurement CI-observable needs the `InstructionsLoaded` record
 * committed from a real session, which is a different piece of work.
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

import { assertScanned, DeadScopeError, reportScanned } from './_lib/scan_scope.js';
import { measure, method_note } from './_lib/token_count.js';
import * as rule_layer_overlap from './_lib/rule_layer_overlap.js';

const PROG = 'check_standing_rule_delivery';
const _HERE = fileURLToPath(import.meta.url);
const REPO_ROOT = path.resolve(path.dirname(_HERE), '..', '..');
const BUDGETS = path.join(REPO_ROOT, 'src', 'config', 'budgets.yml');

/** Placeholder reasons that do not count as a stated cause for a cap raise. */
const PLACEHOLDER_REASONS: readonly string[] = ['', '-', 'tbd', 'todo', 'n/a', 'na', 'none', 'bump'];

interface Budget {
    readonly total_cap_tokens: number;
    readonly warn_threshold: number;
    readonly cap_raise_reason: string;
}

/**
 * Read the `standing_rule_delivery` block from `budgets.yml`.
 *
 * Deliberately a narrow line scan rather than a YAML dependency: this gate must
 * run in a consumer tree where `yaml` may not be installed, and the three keys
 * it needs are flat scalars. An absent block is a configuration error (exit 2),
 * never a permissive default — a budget gate that invents its own ceiling is
 * the same class of failure as one that scans nothing.
 */
export function readBudget(text: string): Budget | null {
    const lines = text.split('\n');
    const start = lines.findIndex((l) => l.trimEnd() === 'standing_rule_delivery:');
    if (start === -1) return null;
    let cap: number | null = null;
    let warn: number | null = null;
    let reason: string | null = null;
    for (let i = start + 1; i < lines.length; i++) {
        const line = lines[i] ?? '';
        if (/^\S/.test(line)) break; // next top-level key ends the block
        const m = /^\s+([a-z_]+):\s*(.*)$/.exec(line);
        if (m === null) continue;
        const [, key, rawValue] = m;
        const value = (rawValue ?? '').trim().replace(/^['"]|['"]$/g, '');
        if (key === 'total_cap_tokens') cap = Number.parseInt(value, 10);
        if (key === 'warn_threshold') warn = Number.parseFloat(value);
        if (key === 'cap_raise_reason') reason = value;
    }
    if (cap === null || Number.isNaN(cap) || warn === null || Number.isNaN(warn) || reason === null) {
        return null;
    }
    return { total_cap_tokens: cap, warn_threshold: warn, cap_raise_reason: reason };
}

/** Is `reason` a real stated cause, or a placeholder? */
export function reasonIsStated(reason: string): boolean {
    return !PLACEHOLDER_REASONS.includes(reason.trim().toLowerCase());
}

/** One measured layer. */
export interface LayerMeasure {
    readonly label: string;
    readonly dir: string;
    readonly files: number;
    readonly tokens: number;
    readonly exact: boolean;
}

function measureFiles(label: string, dir: string, files: ReadonlyMap<string, string>): LayerMeasure {
    const m = measure([...files.values()].join('\n'));
    return { label, dir, files: files.size, tokens: m.tokens_gpt, exact: m.tokens_gpt_exact };
}

/**
 * The one measurement both the gate (`main` below) and the doctor surface
 * (`routing_doctor`) consume — per-layer rule tokens, the overlap between the
 * two layers, and which input the numbers came from. Exported so the doctor
 * reuses it instead of growing a second, drifting copy.
 */
export interface StandingDeliveryMeasure {
    /** Which input produced the numbers — see `instructionsLoadedRecord`. */
    readonly input: 'instructions-loaded' | 'filesystem';
    readonly layers: readonly LayerMeasure[];
    /** Sum over present layers — what the session receives under the host's no-dedup contract. */
    readonly received_tokens: number;
    /** Rules present in BOTH layers (basename match). */
    readonly overlap_rules: number;
    readonly duplicate_rules: number;
    readonly divergent_rules: number;
    /** Tokens of the project-layer copies of overlapping rules — the doubled delivery. */
    readonly overlap_tokens: number;
    readonly exact: boolean;
}

/** Measure both layers once. `null` when neither directory exists (nothing installed). */
export function measureStandingDelivery(
    global_dir: string,
    project_dir: string,
    record_path: string,
): StandingDeliveryMeasure | null {
    const g = rule_layer_overlap.readRuleLayer(global_dir);
    const p = rule_layer_overlap.readRuleLayer(project_dir);
    if (g === null && p === null) return null;
    const layers: LayerMeasure[] = [];
    if (g !== null) layers.push(measureFiles('global', global_dir, g.files));
    if (p !== null) layers.push(measureFiles('project', project_dir, p.files));
    let overlap_rules = 0;
    let duplicate_rules = 0;
    let divergent_rules = 0;
    let overlap_tokens = 0;
    if (g !== null && p !== null) {
        const r = rule_layer_overlap.compareLayers(g.files, p.files);
        overlap_rules = r.overlap.length;
        duplicate_rules = r.duplicate.length;
        divergent_rules = r.divergent.length;
        if (r.overlap.length > 0) {
            overlap_tokens = measure(r.overlap.map((n) => p.files.get(n) ?? '').join('\n')).tokens_gpt;
        }
    }
    return {
        input: fs.existsSync(record_path) ? 'instructions-loaded' : 'filesystem',
        layers,
        received_tokens: layers.reduce((n, l) => n + l.tokens, 0),
        overlap_rules,
        duplicate_rules,
        divergent_rules,
        overlap_tokens,
        exact: layers.every((l) => l.exact),
    };
}

/**
 * Where the loaded-instruction record would live if the host wrote one.
 *
 * Returning a path that does not exist is the expected case today: the
 * `InstructionsLoaded` hook is a host feature this suite does not yet bind, so
 * the gate reports `filesystem` as its input and says so. The probe exists now
 * so that the day the hook is bound, the gate reads the better input without a
 * second change — and so that "which input did this number come from" is
 * answerable rather than assumed.
 */
export function instructionsLoadedRecord(repo_root: string): string {
    return path.join(repo_root, 'agents', 'runtime', 'metrics', 'instructions-loaded.jsonl');
}

export function main(argv: readonly string[] = process.argv.slice(2)): number {
    const unknown = argv.filter((a) => a !== '--quiet');
    if (unknown.length > 0) {
        process.stderr.write(`usage: ${PROG} [--quiet]\n`);
        process.stderr.write(`${PROG}: error: unrecognized arguments: ${unknown.join(' ')}\n`);
        return 2;
    }
    const quiet = argv.includes('--quiet');
    const out = (s: string): void => {
        if (!quiet) process.stdout.write(s);
    };

    let budget: Budget | null;
    try {
        budget = readBudget(fs.readFileSync(BUDGETS, 'utf-8'));
    } catch {
        process.stderr.write(`❌  ${PROG}: cannot read ${path.relative(REPO_ROOT, BUDGETS)}\n`);
        return 2;
    }
    if (budget === null) {
        process.stderr.write(
            `❌  ${PROG}: no complete \`standing_rule_delivery\` block in `
                + `${path.relative(REPO_ROOT, BUDGETS)} — needs total_cap_tokens, `
                + 'warn_threshold and cap_raise_reason. A budget gate does not invent its own ceiling.\n',
        );
        return 2;
    }
    if (!reasonIsStated(budget.cap_raise_reason)) {
        process.stderr.write(
            `❌  ${PROG}: cap_raise_reason is a placeholder (${JSON.stringify(budget.cap_raise_reason)}). `
                + 'Every ceiling value needs a stated cause naming which rule added the tokens and why.\n',
        );
        return 1;
    }

    const measured = measureStandingDelivery(
        path.join(os.homedir(), '.claude', 'rules'),
        path.join(REPO_ROOT, '.claude', 'rules'),
        instructionsLoadedRecord(REPO_ROOT),
    );
    const layers = measured?.layers ?? [];

    const scanned = layers.reduce((n, l) => n + l.files, 0);
    // Two zeroes that mean opposite things, and conflating them is how this gate
    // would become the thing it guards against:
    //
    // - **No layer directory at all** — a machine that has not installed the
    //   suite. Zero rule tokens are delivered, which IS the success state, so
    //   `allowEmpty` is honest here and passes scan_scope's own operational test
    //   ("if the scan root were deleted, would the reason still make sense?" —
    //   yes: nothing installed, nothing loaded).
    // - **A layer directory that exists and holds no `.md`** — a projection that
    //   ran and produced nothing. That is blindness, not cleanliness, and it
    //   stays exit 3.
    const no_layer_present = measured === null;
    try {
        assertScanned({
            gate: PROG,
            scanned,
            units: 'rule file(s) across the layers a session loads',
            roots: ['~/.claude/rules', '.claude/rules'],
            ...(no_layer_present
                ? {
                      allowEmpty:
                          'EMPTY_VALID: neither ~/.claude/rules nor .claude/rules exists on this '
                          + 'machine, so zero rule tokens are delivered — the success state, not a dead scope.',
                  }
                : {}),
        });
    } catch (exc) {
        if (exc instanceof DeadScopeError) {
            process.stderr.write(`❌  ${exc.message}\n`);
            return 3;
        }
        throw exc;
    }
    if (no_layer_present) {
        out(
            `${PROG}: no rule layer on this machine (neither ~/.claude/rules nor .claude/rules) — `
                + 'nothing is delivered, nothing to cap.\n',
        );
        reportScanned({
            gate: PROG,
            scanned: 0,
            units: 'rule file(s)',
            roots: ['~/.claude/rules', '.claude/rules'],
            allowEmpty: 'EMPTY_VALID: no layer installed on this machine.',
        });
        return 0;
    }

    const { input, received_tokens: total, exact } = measured;

    out(`${PROG} · input: ${input} · ${method_note()}\n`);
    if (input === 'filesystem') {
        out(
            '  note: no InstructionsLoaded record present, so this is what the filesystem\n'
                + '        projects, not what the host confirmed loading. A rule projected but never\n'
                + '        loaded, or loaded from an unprojected layer, is invisible to this input.\n',
        );
    }
    for (const l of layers) {
        out(`  ${l.label.padEnd(8)} ${String(l.files).padStart(4)} file(s)  ${String(l.tokens).padStart(8)} tok\n`);
    }

    if (measured.overlap_rules > 0) {
        out(
            `  overlap  ${String(measured.overlap_rules).padStart(4)} rule(s) in both layers `
                + `(${measured.duplicate_rules} duplicate, ${measured.divergent_rules} divergent)\n`,
        );
    }

    const pct = total / budget.total_cap_tokens;
    out(
        `  TOTAL    ${String(total).padStart(13)} tok / ${budget.total_cap_tokens} cap `
            + `(${(pct * 100).toFixed(1)}%)${exact ? '' : ' — proxy, not exact'}\n`,
    );
    reportScanned({
        gate: PROG,
        scanned,
        units: 'rule file(s)',
        roots: ['~/.claude/rules', '.claude/rules'],
    });

    if (pct > 1) {
        process.stderr.write(
            `❌  ${PROG}: ${total} tok of standing rule prose exceeds the ${budget.total_cap_tokens} cap. `
                + 'If two layers overlap, that is the ADR-236 partition not yet armed on this '
                + 'machine: run `agent-config install` so the host layer is fingerprinted in '
                + 'installed.lock, and the next `task generate-tools` withholds the globally-owned '
                + 'artefacts instead of writing a second copy. (Superseded advice: this line used to '
                + 'name `install --layer=<global|project>`, the layer-suppression remedy ADR-226 '
                + 'declined and ADR-236 replaced — a reader following it could not fix the '
                + 'condition.) Otherwise the total is body length, not duplication: scope rules with '
                + '`paths:` or move bodies into the digest.\n',
        );
        return 1;
    }
    if (pct >= budget.warn_threshold) {
        process.stderr.write(
            `⚠️  ${PROG}: ${(pct * 100).toFixed(1)}% of the standing rule cap used `
                + `(warn at ${(budget.warn_threshold * 100).toFixed(0)}%).\n`,
        );
    }
    out(`✅  ${PROG}: standing rule delivery within cap\n`);
    return 0;
}

function _isCliEntry(): boolean {
    try {
        if (process.argv[1] === undefined) return false;
        return fs.realpathSync(_HERE) === fs.realpathSync(path.resolve(process.argv[1]));
    } catch {
        return false;
    }
}

if (_isCliEntry()) {
    process.exit(main());
}
