#!/usr/bin/env tsx
/**
 * check_rule_stub_ceiling — hold a migrated rule at the size its pointer claims.
 *
 * ## The defect
 *
 * 42 of this package's 117 rules carry a line of the shape *"Body migrated to
 * `guideline:X` … Trigger-set above activates this routing on demand"*. The
 * projection half of that pattern is real (`type: manual` → `_is_manual_rule`,
 * `condense.ts`), and the migration ledger (`lint_rule_migration_ledger.ts`)
 * records where each pre-migration heading WENT.
 *
 * **Nothing asserted that a migrated rule stays small.** Migration was executed
 * as an event and never encoded as a state, so those pointers are hand-authored
 * prose no gate reads. The sharpest case, measured at adoption:
 * `src/rules/context-hygiene.md` is 10,988 B and declares its body migrated to
 * `context-hygiene-mechanics.md`, which is 3,491 B — the rule is three times the
 * size of the file it migrated into.
 *
 * The aggregate census ratchet (`check_rule_activation_census`) does not catch
 * this and is not meant to: it pins the CORPUS total with a 2,000-token drift
 * allowance, so one rule growing while another shrinks is a green run. Measured
 * at the time of writing, the corpus sits 411 tokens ABOVE its pinned baseline
 * and that gate is green. Per-rule re-growth under an aggregate cap is the gap.
 *
 * ## What this gate asserts
 *
 * 1. **The pointer's target resolves.** Every `migrated to` / `merged into`
 *    target — markdown link href or backticked `skill:` / `guideline:` /
 *    `context:` / path token — names a file that exists.
 * 2. **The rule is under its own ceiling.** A per-rule exact-BPE token ceiling
 *    read from `src/config/rule-stub-ceilings.json`, generated by
 *    `--write-baseline` and never hand-edited. Shrink-only, same posture as the
 *    census token axis one level finer.
 * 3. **A raise is a stated decision.** A ceiling above the committed one needs a
 *    `history` entry whose `reason` is a real sentence. Raising a ceiling to
 *    clear a red is the config-weakening move this repo blocks by construction.
 *
 * ## What it deliberately does NOT assert
 *
 * - **Not which prose should move.** That is `road-to-standing-context-40k`
 *   step 2.2. This gate measures and holds a line; it never proposes a deletion,
 *   and `preservation-guard` forbids one — a ceiling is satisfied by MOVING.
 * - **Not that a rule at its ceiling is correct.** The ceilings are a
 *   floor-plus-residue snapshot taken at adoption. A rule at its ceiling is not
 *   thereby right, only not worse.
 * - **Not the pointer's semantic accuracy.** That the target resolves is
 *   checkable; that it received the right prose is the migration ledger's
 *   completeness property, already gated next door.
 * - **Not a cross-commit ratchet.** The gate reads ONE tree state, so it cannot
 *   see the previous baseline. "Shrink-only" therefore means: the tree must sit
 *   under the committed ceiling, and every ceiling the history says was RAISED
 *   carries a real reason. A ceiling silently lowered — or raised with no history
 *   entry at all — is a diff-scoped question this gate does not answer; code
 *   review of the baseline diff does. Saying so is the point: implying a
 *   cross-commit guarantee it cannot give is the coverage inflation this repo's
 *   enforcement audit exists to remove.
 * - **Not a phrasing convention.** The pointer set is cross-checked against
 *   `migratedRules()` — the ledger gate's own broad matcher — and a rule that
 *   matcher sees while this one cannot parse is reported as a FINDING, never as
 *   silence. That is the whole mitigation for keying a gate to hand-authored
 *   prose written over months in several phrasings.
 *
 * ## The floor/residue split is reported, not enforced
 *
 * `--report` splits each migrated rule's retained body into **floor** (what
 * `preservation-guard` requires to stay: Iron Law headings at their level, the
 * fenced blocks inside those sections byte-for-byte, capitalised negation
 * clauses, plus the pointer sentence) and **residue** (everything else). The
 * split is a judgment with a mechanical criterion, and it is published per rule
 * WITH the criterion so a reader can disagree with one row without discarding
 * the total. No gate verdict depends on it — it is Phase 3's handover input.
 *
 * Exit codes: 0 = clean, 1 = violations, 2 = usage.
 */
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { GateLedger } from './_lib/gate_ledger.js';
import { runGateCli, runSelfTest, type SelfTestCase } from './_lib/gate_self_test.js';
import { assertScanned, DeadScopeError } from './_lib/scan_scope.js';
import { gpt_tokens, TIKTOKEN_AVAILABLE } from './_lib/token_count.js';
import { migratedRules } from './lint_rule_migration_ledger.js';
import { candidate_paths } from './rule_backlinks.js';

const SCRIPT_REL = path.join('src', 'scripts', 'check_rule_stub_ceiling.ts');
const GATE = 'check_rule_stub_ceiling';
const BASELINE_REL = path.join('src', 'config', 'rule-stub-ceilings.json');
const RULES_REL = path.join('src', 'rules');

/**
 * Floors for the self-test suite, set below the shipped case count on purpose.
 *
 * Eight cases ship and six reject. The floors sit at 7/5 so retiring one case
 * that has genuinely stopped describing the gate does not red the suite, while
 * deleting it down to a happy path — the cheapest route to a green self-test —
 * still fails.
 */
const SELF_TEST_MIN_CASES = 7;
const SELF_TEST_MIN_REJECT = 5;

const ARGV = process.argv.slice(2);
const QUIET = ARGV.includes('--quiet');
const WRITE = ARGV.includes('--write-baseline');
const REPORT = ARGV.includes('--report');

/**
 * A raise reason must be a sentence, not the number restated.
 *
 * The floor is a length plus a digit-density test: "raised to 4200" and "4200"
 * both fail, "moved because X landed and the body grew for reason Y" passes.
 * Mechanical, not editorial — a reason can be wrong, which is a review problem.
 */
const MIN_REASON_CHARS = 40;

/** Phrasings that are present but say nothing. Mirrors the ledger gate's denylist. */
const EMPTY_REASONS = [
    'n/a',
    'none',
    'tbd',
    'see above',
    'no reason',
    'raise',
    'raised',
    'update',
    'updated',
    'adjusted',
    'refresh',
];

/**
 * Matches a migration pointer and captures its target.
 *
 * Two target shapes ship in the corpus: a markdown link, where the href is the
 * target and the label is decorative, and a bare backticked token. Anchored on
 * the verb rather than on `Body …` because one live phrasing is mid-sentence
 * ("Portability body migrated to X. Sync body migrated to Y") and two are
 * soft-wrapped across lines — so this runs over the joined body.
 */
const POINTER_RE = /\b(?:migrated to|merged into)\s+(?:\[[^\]]*\]\(([^)\s]+)\)|`([^`]+)`)/gi;

/** An Iron Law heading at any level, including the numbered variants. */
const IRON_LAW_HEADING_RE = /^#{1,6}\s+(?:The\s+)?Iron\s+Laws?\b/i;

/** A capitalised negation clause — the load-bearing exception denials. */
const NEGATION_RE = /\b(?:NEVER|NO|NOT|DO NOT)\b/;

export interface PointerRow {
    /** Rule stem, e.g. `context-hygiene`. */
    rule: string;
    /** Raw target as written in the pointer. */
    target: string;
    /** Repo-relative path it resolved to, or null when unresolved. */
    resolved: string | null;
    /** Candidate paths tried, for the failure message. */
    tried: string[];
}

export interface RuleRow {
    rule: string;
    /** Exact-BPE tokens of the whole file, frontmatter included — the payload. */
    tokens: number;
    /**
     * Tokens of the YAML frontmatter.
     *
     * Reported as its own column so `fm + floor + residue` reconciles against
     * `tokens`. Without it the table's columns do not add up, which invites a
     * reader to distrust every row — and the frontmatter is real payload: it is
     * what the emitter reads to decide whether the rule loads at all.
     */
    frontmatter_tokens: number;
    /** Tokens of lines classified floor by the criterion above. */
    floor_tokens: number;
    /** Tokens of everything else in the body. */
    residue_tokens: number;
    pointers: PointerRow[];
    /** True when `migratedRules()` sees this rule but POINTER_RE parsed no target. */
    unparsed: boolean;
}

/**
 * Resolve a pointer target to a repo-relative path.
 *
 * Reuses `rule_backlinks.candidate_paths` for the `skill:` / `guideline:` /
 * `context:` / `contract:` / repo-path shapes rather than restating them, and
 * `check_references`'s prefix strategy for relative hrefs rather than inventing
 * a second one. A bare word with no shape falls back to a sibling rule, the one
 * form `brand-consistency` uses ("merged into `brand-source-of-truth`").
 *
 * **Why a relative href is not resolved relative to `src/rules/`.** That was the
 * first implementation and it reported 12 of 44 pointers broken — a false red.
 * Rule bodies are authored for the PROJECTED tree, where `../docs/` is the
 * sibling docs directory; under `src/rules/` the same href points at
 * `src/docs/`, which does not exist. `check_references` already solved this by
 * stripping leading `./` / `../` and trying `[root, dist/agent-src, src,
 * src/agent-src]`, and a second convention here would disagree with the gate
 * consumers already trust. Adopted verbatim.
 */
export function resolvePointer(root: string, raw: string): { resolved: string | null; tried: string[] } {
    // Anchors are part of the link, never part of the file identity.
    const bare = raw.split('#')[0]!.trim();
    if (bare === '') return { resolved: null, tried: [] };

    const tried: string[] = [];

    if (bare.startsWith('.') || bare.includes('/')) {
        const stripped = bare.replace(/^[./]+/, '');
        for (const prefix of ['', 'dist/agent-src', 'src', 'src/agent-src']) {
            const rel = path.normalize(path.join(prefix, stripped));
            tried.push(rel);
            if (fs.existsSync(path.join(root, rel))) return { resolved: rel, tried };
        }
        // Also as written from the rule's own directory, which is how a
        // same-directory sibling link (`brand-source-of-truth.md`) resolves.
        const sibling = path.normalize(path.join(RULES_REL, bare));
        tried.push(sibling);
        if (fs.existsSync(path.join(root, sibling))) return { resolved: sibling, tried };
    }

    const shaped = candidate_paths(bare);
    if (shaped !== null) {
        for (const rel of shaped) {
            tried.push(rel);
            if (fs.existsSync(path.join(root, rel))) return { resolved: rel, tried };
        }
    }

    // Bare stem → a sibling rule.
    if (/^[a-z0-9][a-z0-9_.-]*$/i.test(bare)) {
        const rel = path.join(RULES_REL, `${bare.replace(/\.md$/, '')}.md`);
        tried.push(rel);
        if (fs.existsSync(path.join(root, rel))) return { resolved: rel, tried };
    }

    return { resolved: null, tried };
}

/** Split a rule file into its YAML frontmatter and its body. */
function splitFrontmatter(text: string): { frontmatter: string; body: string } {
    if (!text.startsWith('---')) return { frontmatter: '', body: text };
    const end = text.indexOf('\n---', 3);
    if (end === -1) return { frontmatter: '', body: text };
    const nl = text.indexOf('\n', end + 1);
    if (nl === -1) return { frontmatter: text, body: '' };
    return { frontmatter: text.slice(0, nl + 1), body: text.slice(nl + 1) };
}

/**
 * Split a body into floor and residue lines by the stated criterion.
 *
 * Floor: an Iron Law heading; every line of a fenced block opened while inside
 * an Iron Law section; any line carrying a capitalised negation clause; the
 * pointer sentence itself. Everything else is residue.
 *
 * The Iron-Law-section boundary is the next heading at the same level or
 * shallower — a `###` inside an `## Iron Law` stays inside it, which matters
 * because demotion is the norm in these files.
 */
export function splitFloorResidue(body: string): { floor: string[]; residue: string[] } {
    const floor: string[] = [];
    const residue: string[] = [];
    let ironLevel: number | null = null;
    let inFence = false;

    for (const line of body.split('\n')) {
        const fence = /^\s*(?:```|~~~)/.test(line);
        const heading = /^(#{1,6})\s/.exec(line);

        if (inFence) {
            (ironLevel !== null ? floor : residue).push(line);
            if (fence) inFence = false;
            continue;
        }

        if (IRON_LAW_HEADING_RE.test(line)) {
            ironLevel = heading?.[1]!.length ?? 2;
            floor.push(line);
            continue;
        }

        if (heading !== null && ironLevel !== null && heading[1]!.length <= ironLevel) {
            ironLevel = null;
        }

        if (fence) {
            inFence = true;
            (ironLevel !== null ? floor : residue).push(line);
            continue;
        }

        if (ironLevel !== null || NEGATION_RE.test(line) || POINTER_RE.test(line)) {
            POINTER_RE.lastIndex = 0;
            floor.push(line);
            continue;
        }
        POINTER_RE.lastIndex = 0;
        residue.push(line);
    }

    return { floor, residue };
}

/** Measure every rule carrying a migration pointer. */
export function readRules(root: string): { rows: RuleRow[]; scanned: number } {
    const dir = path.join(root, RULES_REL);
    let names: string[];
    try {
        names = fs.readdirSync(dir).filter((n) => n.endsWith('.md')).sort();
    } catch {
        return { rows: [], scanned: 0 };
    }

    // The ledger gate's broad matcher is the denominator: a rule it sees and this
    // gate cannot parse is a phrasing drift, reported rather than skipped.
    const broad = new Set(migratedRules(root));
    const rows: RuleRow[] = [];

    for (const n of names) {
        const stem = n.slice(0, -3);
        const text = fs.readFileSync(path.join(dir, n), 'utf8');
        const joined = text.replace(/\s*\n\s*/g, ' ');

        const pointers: PointerRow[] = [];
        POINTER_RE.lastIndex = 0;
        for (const m of joined.matchAll(POINTER_RE)) {
            const raw = (m[1] ?? m[2] ?? '').trim();
            const { resolved, tried } = resolvePointer(root, raw);
            pointers.push({ rule: stem, target: raw, resolved, tried });
        }

        if (pointers.length === 0 && !broad.has(stem)) continue;

        const { frontmatter, body } = splitFrontmatter(text);
        const { floor, residue } = splitFloorResidue(body);
        rows.push({
            rule: stem,
            tokens: gpt_tokens(text).tokens,
            frontmatter_tokens: gpt_tokens(frontmatter).tokens,
            floor_tokens: gpt_tokens(floor.join('\n')).tokens,
            residue_tokens: gpt_tokens(residue.join('\n')).tokens,
            pointers,
            unparsed: pointers.length === 0,
        });
    }

    return { rows, scanned: names.length };
}

interface Ceilings {
    _comment: string;
    measured_at_commit: string;
    tokens_exact: boolean;
    /** rule stem → exact-BPE token ceiling. */
    ceilings: Record<string, number>;
    history: { date: string; rule: string; from: number; to: number; reason: string }[];
}

function ceilingComment(): string {
    return (
        'Per-rule stub ceilings (road-to-rule-stub-projection Phase 2). One exact-BPE token ' +
        'ceiling per rule carrying a migration pointer. SHRINK-ONLY: a rule may fall below its ' +
        'ceiling freely, and may not rise above it. Raising a ceiling to clear a failing check ' +
        'is the config-weakening move this repo blocks by construction — every raise needs a ' +
        '`history` entry whose `reason` is a real sentence. The ceilings are a floor-plus-residue ' +
        'SNAPSHOT taken at adoption, not a target: a rule at its ceiling is not thereby correct, ' +
        'only not worse. Regenerate with `check_rule_stub_ceiling --write-baseline`; never ' +
        'hand-edit the counts.'
    );
}

/**
 * A raise reason must be a sentence, not the number restated.
 *
 * Mechanical, not editorial: a length floor, a denylist of known-empty
 * phrasings, and a letters-remain test so "raised to 4200" and "4200" both fail
 * while a real explanation passes. A reason can still be WRONG — that is a
 * review problem, and no lint can be its judge.
 */
export function isRealReason(reason: unknown): boolean {
    if (typeof reason !== 'string') return false;
    const trimmed = reason.trim();
    if (trimmed.length < MIN_REASON_CHARS) return false;
    if (EMPTY_REASONS.includes(trimmed.toLowerCase())) return false;
    return /[a-z]{4}/i.test(trimmed.replace(/\d/g, ''));
}

/** Markdown table for the Phase-0 evidence artifact. */
export function renderReport(rows: RuleRow[]): string {
    const total = rows.reduce((a, r) => a + r.tokens, 0);
    const fm = rows.reduce((a, r) => a + r.frontmatter_tokens, 0);
    const floor = rows.reduce((a, r) => a + r.floor_tokens, 0);
    const residue = rows.reduce((a, r) => a + r.residue_tokens, 0);
    const out: string[] = [];
    out.push(`| rule | tokens | frontmatter | floor | residue | pointer target | resolves |`);
    out.push(`|---|---:|---:|---:|---:|---|---|`);
    for (const r of rows.slice().sort((a, b) => b.residue_tokens - a.residue_tokens)) {
        const targets = r.pointers.length === 0 ? '(unparsed)' : r.pointers.map((p) => `\`${p.target}\``).join(' · ');
        const ok = r.pointers.length === 0 ? '—' : r.pointers.every((p) => p.resolved !== null) ? 'yes' : 'NO';
        out.push(
            `| \`${r.rule}\` | ${r.tokens} | ${r.frontmatter_tokens} | ${r.floor_tokens} | ` +
                `${r.residue_tokens} | ${targets} | ${ok} |`,
        );
    }
    out.push(
        `| **total (${rows.length} rules)** | **${total}** | **${fm}** | **${floor}** | ` +
            `**${residue}** | | |`,
    );
    // BPE is not additive across a split: merges that span a segment boundary are
    // lost when the segments are encoded separately. Stating the residual is the
    // honest form — a reader who adds the columns WILL find it, and a table that
    // silently does not reconcile is worse than one that says by how much.
    const parts = fm + floor + residue;
    out.push('');
    out.push(
        `Column residual: \`frontmatter + floor + residue\` = ${parts} against ` +
            `${total} whole-file tokens (${parts - total >= 0 ? '+' : ''}${parts - total}, ` +
            `${(Math.abs(parts - total) / Math.max(total, 1) * 100).toFixed(2)} %). ` +
            'BPE is not additive across segment boundaries; the whole-file column is the ' +
            'one the ceilings are keyed on.',
    );
    return out.join('\n');
}

export function main(): number {
    if (ARGV.includes('--self-test')) {
        return selfTest(path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..'));
    }
    const root = process.cwd();

    let reading: { rows: RuleRow[]; scanned: number };
    try {
        reading = readRules(root);
        assertScanned({
            gate: GATE,
            scanned: reading.scanned,
            units: 'rule file(s)',
            roots: [RULES_REL],
        });
    } catch (err) {
        if (err instanceof DeadScopeError) {
            process.stderr.write(`❌  ${err.message}\n`);
            return 1;
        }
        throw err;
    }

    const rows = reading.rows;

    if (REPORT) {
        process.stdout.write(`${renderReport(rows)}\n`);
        return 0;
    }

    const baseline_path = path.join(root, BASELINE_REL);

    if (WRITE) {
        const prior: Ceilings | null = fs.existsSync(baseline_path)
            ? (JSON.parse(fs.readFileSync(baseline_path, 'utf8')) as Ceilings)
            : null;
        const ceilings: Record<string, number> = {};
        for (const r of rows.slice().sort((a, b) => a.rule.localeCompare(b.rule))) {
            ceilings[r.rule] = r.tokens;
        }
        const next: Ceilings = {
            _comment: ceilingComment(),
            measured_at_commit: process.env['AGENT_CONFIG_BASELINE_COMMIT'] ?? 'unrecorded',
            tokens_exact: TIKTOKEN_AVAILABLE,
            ceilings,
            history: prior?.history ?? [],
        };
        fs.writeFileSync(baseline_path, `${JSON.stringify(next, null, 4)}\n`);
        process.stdout.write(
            `✅  ${GATE}: baseline written — ${Object.keys(ceilings).length} migrated rule(s) ` +
                `(${next.tokens_exact ? 'exact BPE' : 'character proxy'}).\n`,
        );
        return 0;
    }

    if (!fs.existsSync(baseline_path)) {
        process.stderr.write(
            `❌  ${GATE}: no baseline at ${BASELINE_REL}. Run with --write-baseline once, ` +
                'commit the file, and the ceilings are live from then on.\n',
        );
        return 1;
    }

    const base = JSON.parse(fs.readFileSync(baseline_path, 'utf8')) as Ceilings;
    const failures: string[] = [];
    const ledger = new GateLedger(GATE);
    ledger.plan(rows.map((r) => r.rule));

    // A method change would report a measurement delta as a payload delta.
    // Say so instead of ratcheting — same posture as the census weight axis.
    if (base.tokens_exact !== TIKTOKEN_AVAILABLE) {
        for (const r of rows) ledger.complete(r.rule);
        ledger.report();
        process.stderr.write(
            `❌  ${GATE}: token measurement METHOD changed (baseline ` +
                `${base.tokens_exact ? 'exact' : 'proxy'} → current ` +
                `${TIKTOKEN_AVAILABLE ? 'exact' : 'proxy'}). The ceilings are UNRESOLVED, not ` +
                'red: re-anchor in the same environment rather than reading a method delta as ' +
                'a corpus delta.\n',
        );
        return 1;
    }

    // Every declared raise must carry a real reason, checked INDEPENDENTLY of
    // whether any rule is currently over its ceiling.
    //
    // The first implementation consulted the reason only inside the
    // `tokens > ceiling` branch, which made it unreachable in practice: a raise
    // is precisely the act that puts the rule back UNDER its ceiling, so the
    // branch that would have checked the reason never ran. The gate's own
    // self-test caught it. The requirement belongs to the baseline's integrity,
    // not to the rule's current size.
    const raised = new Map<string, { from: number; to: number; reason: string }>();
    for (const h of base.history ?? []) {
        if (typeof h.rule !== 'string' || !(h.to > h.from)) continue;
        raised.set(h.rule, h);
        if (!isRealReason(h.reason)) {
            failures.push(
                `baseline history raises \`${h.rule}\` ${h.from} → ${h.to} with no real reason ` +
                    `(got ${JSON.stringify(h.reason ?? null)}). A raise is a stated decision: ` +
                    `write the sentence that says what landed and why the ceiling moves with it. ` +
                    `Raising a ceiling to clear a red is the config-weakening move this repo ` +
                    `blocks by construction.`,
            );
        }
        if (base.ceilings[h.rule] !== undefined && base.ceilings[h.rule]! !== h.to) {
            failures.push(
                `baseline history says \`${h.rule}\` was raised to ${h.to}, but its committed ` +
                    `ceiling is ${base.ceilings[h.rule]!}. The history and the ceilings disagree, ` +
                    `which is the signature of a hand-edited count — regenerate with ` +
                    `--write-baseline instead of editing the number.`,
            );
        }
    }

    for (const r of rows) {
        const reasons: string[] = [];

        if (r.unparsed) {
            reasons.push(
                'carries a migration line the ledger gate sees, but no target this gate can ' +
                    'parse. A reworded pointer must surface as a finding, never as silence — ' +
                    'either restore a parseable target or extend POINTER_RE with the new form',
            );
        }
        for (const p of r.pointers) {
            if (p.resolved === null) {
                reasons.push(
                    `migration pointer target \`${p.target}\` resolves to nothing (tried: ` +
                        `${p.tried.length > 0 ? p.tried.join(', ') : 'no known shape'})`,
                );
            }
        }

        const ceiling = base.ceilings[r.rule];
        if (ceiling === undefined) {
            reasons.push(
                `no ceiling in ${BASELINE_REL}. A newly migrated rule needs one: re-anchor with ` +
                    '--write-baseline in the same commit that adds the pointer',
            );
        } else if (r.tokens > ceiling) {
            const entry = raised.get(r.rule);
            // A raise already validated above may cover this overflow, but only if
            // it actually reaches the current size. An entry stopping short of it
            // is a partial raise and the residual is still unstated.
            const covered = entry !== undefined && entry.to >= r.tokens && isRealReason(entry.reason);
            if (!covered) {
                reasons.push(
                    `grew past its ceiling (${ceiling} → ${r.tokens} tokens, +${r.tokens - ceiling}). ` +
                        'A migrated rule is held at the size its pointer claims. Move the prose to ' +
                        'the pointer target — never delete it, `preservation-guard` binds — or raise ' +
                        'the ceiling with a `history` entry whose reason is a real sentence',
                );
            }
        }

        if (reasons.length > 0) {
            ledger.fail(r.rule, reasons[0]!);
            for (const reason of reasons) failures.push(`\`${r.rule}\`: ${reason}`);
        } else {
            ledger.complete(r.rule);
        }
    }

    ledger.report();

    if (failures.length > 0) {
        process.stderr.write(`❌  ${GATE}: a migrated rule stopped matching its own pointer.\n\n`);
        for (const f of failures) process.stderr.write(`    • ${f}\n`);
        process.stderr.write(
            '\n    The pointer is a claim the rule makes about itself. This gate holds it —\n' +
                '    the point is that a change is stated, not that it is forbidden.\n',
        );
        return 1;
    }

    // Exactly one `scanned: <N>` line, on both paths and regardless of --quiet:
    // a gate that goes blind must be detectable on the run where it says nothing
    // else. Contract rule 1 of `src/config/gate-coverage.yml`.
    process.stdout.write(`scanned: ${reading.scanned}\n`);

    if (!QUIET) {
        const residue = rows.reduce((a, r) => a + r.residue_tokens, 0);
        process.stdout.write(
            `✅  ${GATE}: ${rows.length} migrated rule(s) under ceiling · ` +
                `${rows.reduce((a, r) => a + r.pointers.length, 0)} pointer(s) resolved · ` +
                `${residue} residue tokens ` +
                `(${TIKTOKEN_AVAILABLE ? 'exact BPE' : 'character proxy'}) · ` +
                `${reading.scanned} rule file(s).\n`,
        );
    }
    return 0;
}

/** A migrated rule whose pointer resolves, used as the accept fixture. */
const FIXTURE_TARGET_REL = path.join('docs', 'guidelines', 'alpha-mechanics.md');
const FIXTURE_OK = [
    '---',
    'type: "auto"',
    '---',
    '',
    '# Alpha',
    '',
    '## The Iron Law',
    '',
    '```',
    'NEVER DO THE WRONG THING.',
    '```',
    '',
    'Body migrated to `guideline:alpha-mechanics` (per P4 of the router roadmap).',
    '',
].join('\n');

interface FixtureShape {
    /** Write the rule + its pointer target. Off for the dead-scope case. */
    rules: boolean;
    /** Write the pointer target file. Off for the unresolved-pointer case. */
    target?: boolean;
    /** Write a baseline at all. Off for the missing-baseline case. */
    baseline: boolean;
    /** Extra body appended to the rule AFTER the baseline is derived. */
    pad?: string;
    /** Replace the pointer line, to test the unparsed-phrasing path. */
    rewordPointer?: string;
    /** Mutate the derived baseline before writing. */
    tamper?: (b: Ceilings) => void;
}

/**
 * Build a throwaway tree the gate can run against.
 *
 * The baseline is DERIVED by the same `readRules` the gate uses, then the rule is
 * optionally padded. Hand-writing an expected token total would make the accept
 * case a test of my arithmetic rather than of the gate.
 */
function buildFixture(dir: string, shape: FixtureShape): string {
    fs.mkdirSync(path.join(dir, RULES_REL), { recursive: true });
    fs.mkdirSync(path.join(dir, 'src', 'config'), { recursive: true });
    fs.mkdirSync(path.join(dir, path.dirname(FIXTURE_TARGET_REL)), { recursive: true });

    const rulePath = path.join(dir, RULES_REL, 'alpha.md');
    if (shape.rules) {
        let body = FIXTURE_OK;
        if (shape.rewordPointer !== undefined) {
            body = body.replace(
                'Body migrated to `guideline:alpha-mechanics` (per P4 of the router roadmap).',
                shape.rewordPointer,
            );
        }
        fs.writeFileSync(rulePath, body);
    }
    if (shape.target !== false) {
        fs.writeFileSync(path.join(dir, FIXTURE_TARGET_REL), '# Alpha mechanics\n');
    }

    if (shape.baseline) {
        const derived = shape.rules ? readRulesIn(dir) : [];
        const ceilings: Record<string, number> = {};
        for (const r of derived) ceilings[r.rule] = r.tokens;
        const base: Ceilings = {
            _comment: 'self-test fixture',
            measured_at_commit: 'fixture',
            tokens_exact: TIKTOKEN_AVAILABLE,
            ceilings,
            history: [],
        };
        shape.tamper?.(base);
        fs.writeFileSync(path.join(dir, BASELINE_REL), `${JSON.stringify(base, null, 4)}\n`);
    }

    // Padding lands AFTER the baseline so the fixture grows against its own ceiling.
    if (shape.rules && shape.pad !== undefined) {
        fs.appendFileSync(rulePath, shape.pad);
    }
    return dir;
}

/** `readRules` against an arbitrary root — the fixture builder's measurement path. */
function readRulesIn(dir: string): RuleRow[] {
    return readRules(dir).rows;
}

/**
 * Prove the gate discriminates rather than merely exits.
 *
 * The four rejecting cases are the four ways this gate is worth having: a broken
 * pointer target, a rule grown past its ceiling, a raise with no real reason, and
 * the dead scan root. The dead-root case is the one a refactor is most likely to
 * break silently — a gate that scans nothing and exits green is exactly what
 * `assertScanned` exists for.
 */
export function selfTest(repoRoot: string): number {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'rsc-selftest-'));
    const run = (shape: FixtureShape): number => {
        const work = buildFixture(fs.mkdtempSync(path.join(root, 'case-')), shape);
        return runGateCli(repoRoot, SCRIPT_REL, ['--quiet'], work);
    };
    const padding = `\n${'Filler prose that is neither an Iron Law nor a negation clause. '.repeat(40)}\n`;

    const cases: SelfTestCase[] = [
        {
            name: 'a migrated rule at its ceiling with a resolving pointer passes',
            expect: 'accept',
            run: () => run({ rules: true, baseline: true }),
        },
        {
            name: 'a pointer whose target does not resolve is REFUSED',
            expect: 'reject',
            run: () => run({ rules: true, baseline: true, target: false }),
        },
        {
            name: 'a migrated rule padded past its ceiling is REFUSED',
            expect: 'reject',
            run: () => run({ rules: true, baseline: true, pad: padding }),
        },
        // The next two isolate the REASON requirement from the size check: no
        // padding, so the rule sits comfortably under its raised ceiling and the
        // only thing separating accept from reject is the sentence. That framing
        // is the whole point — the first implementation checked the reason only
        // when the rule was over its ceiling, which a raise by definition fixes,
        // so the check was unreachable and this suite is what surfaced it.
        {
            name: 'a raise whose reason is empty is REFUSED even when nothing is over its ceiling',
            expect: 'reject',
            run: () =>
                run({
                    rules: true,
                    baseline: true,
                    tamper: (b) => {
                        const at = b.ceilings['alpha'] ?? 0;
                        b.ceilings['alpha'] = at + 10_000;
                        b.history = [
                            { date: '2026-08-17', rule: 'alpha', from: at, to: at + 10_000, reason: 'raise' },
                        ];
                    },
                }),
        },
        {
            name: 'the same raise WITH a real reason sentence passes',
            expect: 'accept',
            run: () =>
                run({
                    rules: true,
                    baseline: true,
                    tamper: (b) => {
                        const at = b.ceilings['alpha'] ?? 0;
                        b.ceilings['alpha'] = at + 10_000;
                        b.history = [
                            {
                                date: '2026-08-17',
                                rule: 'alpha',
                                from: at,
                                to: at + 10_000,
                                reason:
                                    'A measured finding landed in this rule and its worked example ' +
                                    'is load-bearing, so the ceiling moves with the authored change.',
                            },
                        ];
                    },
                }),
        },
        {
            name: 'a history entry disagreeing with the committed ceiling is REFUSED',
            expect: 'reject',
            run: () =>
                run({
                    rules: true,
                    baseline: true,
                    tamper: (b) => {
                        const at = b.ceilings['alpha'] ?? 0;
                        b.history = [
                            {
                                date: '2026-08-17',
                                rule: 'alpha',
                                from: at,
                                to: at + 5_000,
                                reason:
                                    'A real sentence, so the only thing wrong here is that the ' +
                                    'committed ceiling was never regenerated to match the claim.',
                            },
                        ];
                    },
                }),
        },
        {
            // Risk 3 of the roadmap: 44 pointers were hand-written over months in
            // several phrasings, so a gate keyed to one phrasing silently stops
            // seeing the others. This case pins the opposite behaviour — a rule the
            // ledger's broad matcher sees and this gate cannot parse is a FINDING.
            name: 'a reworded pointer this gate cannot parse is REFUSED, not silently skipped',
            expect: 'reject',
            run: () =>
                run({
                    rules: true,
                    baseline: true,
                    rewordPointer: 'The body was migrated to the guideline on alpha mechanics.',
                }),
        },
        {
            name: 'a dead scan root is REFUSED rather than reported clean',
            expect: 'reject',
            run: () => run({ rules: false, baseline: true }),
        },
    ];

    return runSelfTest({
        gate: GATE,
        cases,
        minCases: SELF_TEST_MIN_CASES,
        minRejectCases: SELF_TEST_MIN_REJECT,
    });
}

if (process.argv[1] && import.meta.url === pathToFileURL(fileURLToPath(import.meta.url)).href) {
    const invoked = path.resolve(process.argv[1]);
    const self = path.resolve(fileURLToPath(import.meta.url));
    if (invoked === self) process.exit(main());
}
