#!/usr/bin/env tsx
/** Generate agents/evidence/notes/discovery-baseline.md for Phase 0.1.
 *
 * TypeScript twin of `src/scripts/gen_discovery_baseline.py` (ADR-200, Phase 8
 * / Wave 8h). Mirrors the Python CLI contract EXACTLY — no flags, exit 0,
 * byte-identical stdout (`wrote {dest} — {n} lines`) and byte-identical written
 * `discovery-baseline.md` (except the generated UTC timestamp, which is
 * non-deterministic and excluded from golden parity). No behaviour changes:
 * the docstring says `agents/evidence/notes/…` but the script writes to
 * `agents/notes/discovery-baseline.md` — that latent mismatch is preserved.
 *
 * NON-DETERMINISM: the `> Generated by … on <UTC timestamp>` line stamps the
 * current UTC time. Golden parity excludes it; every other line is
 * deterministic given a fixed source tree.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import process from 'node:process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const _HERE = fileURLToPath(import.meta.url);

// Python: ROOT = pathlib.Path(__file__).resolve().parents[2]
const ROOT = path.resolve(_HERE, '..', '..', '..');
const SRC = path.join(ROOT, '.agent-src.uncondensed');

function _frontmatter(p: string): Record<string, string> {
    let text: string;
    try {
        text = fs.readFileSync(p, 'utf-8');
    } catch {
        // errors="replace" — fall back to a best-effort latin1 read.
        text = fs.readFileSync(p, 'latin1');
    }
    const m = /^---\n([\s\S]*?)\n---\n/.exec(text);
    if (!m) {
        return {};
    }
    const out: Record<string, string> = {};
    for (const line of (m[1] as string).split('\n')) {
        if (line.includes(':') && !line.startsWith(' ')) {
            const idx = line.indexOf(':');
            const k = line.slice(0, idx);
            const v = line.slice(idx + 1);
            out[k.trim()] = _stripQuotes(v.trim());
        }
    }
    return out;
}

/** Mirror Python `.strip('"').strip("'")` — strip leading/trailing of each char class. */
function _stripQuotes(s: string): string {
    let out = s.replace(/^"+/, '').replace(/"+$/, '');
    out = out.replace(/^'+/, '').replace(/'+$/, '');
    return out;
}

function _isFile(p: string): boolean {
    try {
        return fs.statSync(p).isFile();
    } catch {
        return false;
    }
}

function _exists(p: string): boolean {
    return fs.existsSync(p);
}

/** Recursive `Path.rglob(pattern)` where pattern is an exact basename. */
function _rglobName(root: string, name: string): string[] {
    const out: string[] = [];
    function walk(dir: string): void {
        let entries: fs.Dirent[];
        try {
            entries = fs.readdirSync(dir, { withFileTypes: true });
        } catch {
            return;
        }
        for (const ent of entries) {
            const full = path.join(dir, ent.name);
            if (ent.isDirectory()) {
                walk(full);
            } else if (ent.name === name) {
                out.push(full);
            }
        }
    }
    walk(root);
    return out;
}

/** Recursive `Path.rglob("*.md")`. */
function _rglobMd(root: string): string[] {
    const out: string[] = [];
    function walk(dir: string): void {
        let entries: fs.Dirent[];
        try {
            entries = fs.readdirSync(dir, { withFileTypes: true });
        } catch {
            return;
        }
        for (const ent of entries) {
            const full = path.join(dir, ent.name);
            if (ent.isDirectory()) {
                walk(full);
            } else if (ent.name.endsWith('.md')) {
                out.push(full);
            }
        }
    }
    walk(root);
    return out;
}

/** Recursive `Path.rglob("*")` — every descendant (dirs + files). */
function _rglobAll(root: string): string[] {
    const out: string[] = [];
    function walk(dir: string): void {
        let entries: fs.Dirent[];
        try {
            entries = fs.readdirSync(dir, { withFileTypes: true });
        } catch {
            return;
        }
        for (const ent of entries) {
            const full = path.join(dir, ent.name);
            out.push(full);
            if (ent.isDirectory()) {
                walk(full);
            }
        }
    }
    walk(root);
    return out;
}

function _comparePathComponents(a: string, b: string): number {
    const pa = a.split(path.sep);
    const pb = b.split(path.sep);
    const n = Math.min(pa.length, pb.length);
    for (let i = 0; i < n; i += 1) {
        const x = pa[i] as string;
        const y = pb[i] as string;
        if (x !== y) {
            return x < y ? -1 : 1;
        }
    }
    return pa.length - pb.length;
}

function _sorted(items: string[]): string[] {
    const out = [...items];
    out.sort(_comparePathComponents);
    return out;
}

function _relativeTo(p: string, root: string): string {
    return path.relative(root, p);
}

/** Mirror `datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')`. */
function _utcStamp(): string {
    const d = new Date();
    const pad = (n: number, w = 2): string => String(n).padStart(w, '0');
    return (
        `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}T` +
        `${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}Z`
    );
}

export function main(): number {
    const skills = _sorted(_rglobName(path.join(SRC, 'skills'), 'SKILL.md'));
    const rules = _sorted(_rglobMd(path.join(SRC, 'rules')));
    const commands = _sorted(_rglobMd(path.join(SRC, 'commands')));
    let templates = _exists(path.join(SRC, 'templates')) ? _sorted(_rglobAll(path.join(SRC, 'templates'))) : [];
    templates = templates.filter((p) => _isFile(p));

    // Counter[str] with insertion order = sorted-skills iteration order.
    const domains = new Map<string, number>();
    let noDomain = 0;
    for (const s of skills) {
        const fm = _frontmatter(s);
        const d = fm.domain;
        if (d) {
            domains.set(d, (domains.get(d) ?? 0) + 1);
        } else {
            noDomain += 1;
        }
    }

    const out: string[] = [];
    out.push('# Discovery Baseline — Inventory (Phase 0.1)\n');
    out.push(
        '> Generated by `scripts/gen_discovery_baseline.py` on ' + `${_utcStamp()}.\n`,
    );
    out.push(
        '> Frozen reference for the Phase 2 scanner — the `no domain` tally below must match the\n' +
            "> first scanner run's `unassigned[]` count within ±5% (Phase 2.4 acceptance).\n",
    );

    out.push('## Counts by category\n');
    out.push('| Category | Path | Count |');
    out.push('|---|---|---|');
    out.push(`| Skills | \`.agent-src.uncondensed/skills/*/SKILL.md\` | ${skills.length} |`);
    out.push(`| Rules | \`.agent-src.uncondensed/rules/**/*.md\` | ${rules.length} |`);
    out.push(`| Commands | \`.agent-src.uncondensed/commands/**/*.md\` | ${commands.length} |`);
    out.push(`| Templates | \`.agent-src.uncondensed/templates/**/*\` | ${templates.length} |`);
    out.push('');

    out.push('## Distinct `domain:` values (skills)\n');
    for (const [d, n] of _mostCommon(domains)) {
        out.push(`- \`${d}\` — ${n} skill(s)`);
    }
    out.push('');

    out.push('## Skills without `domain:` (Phase 0.1 baseline)\n');
    out.push(`- Count: **${noDomain}** (target for Phase 2.4 \`unassigned[]\` tally ±5%)`);
    out.push('');

    out.push('## Sample frontmatter keys (first 10 skills)\n');
    out.push('| File | name | source | domain | other keys |');
    out.push('|---|---|---|---|---|');
    const interesting = new Set(['status', 'tier', 'recommended_for_user_types', 'cluster', 'skills']);
    for (const s of skills.slice(0, 10)) {
        const fm = _frontmatter(s);
        const other = Object.keys(fm)
            .filter((k) => interesting.has(k))
            .sort()
            .join(',');
        const rel = _relativeTo(s, SRC);
        out.push(
            `| \`${rel}\` | ${fm.name ?? ''} | ${fm.source ?? ''} | ` +
                `${fm.domain ?? ''} | ${other} |`,
        );
    }
    out.push('');

    out.push('## Sample rules (first 10)\n');
    out.push('| File | type | tier | source |');
    out.push('|---|---|---|---|');
    for (const r of rules.slice(0, 10)) {
        const fm = _frontmatter(r);
        const rel = _relativeTo(r, SRC);
        out.push(`| \`${rel}\` | ${fm.type ?? ''} | ${fm.tier ?? ''} | ${fm.source ?? ''} |`);
    }
    out.push('');

    out.push('## Sample commands (first 10)\n');
    out.push('| File | name | tier | cluster |');
    out.push('|---|---|---|---|');
    for (const c of commands.slice(0, 10)) {
        const fm = _frontmatter(c);
        const rel = _relativeTo(c, SRC);
        out.push(`| \`${rel}\` | ${fm.name ?? ''} | ${fm.tier ?? ''} | ${fm.cluster ?? ''} |`);
    }
    out.push('');

    out.push('## Notes\n');
    out.push('- Every skill carries `domain:` today — Phase 4 mapping uses it as primary signal.');
    out.push('- Rules use `type` (always | auto) + `tier` (safety-floor | kernel | …); no `domain:` today.');
    out.push('- Commands use `tier` + `cluster`; no `domain:` today.');
    out.push('- Templates have no consistent frontmatter; Phase 4 quarantines them in `unassigned-artefacts.yml`.');
    out.push('');

    const dest = path.join(ROOT, 'agents', 'notes', 'discovery-baseline.md');
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, out.join('\n'), 'utf-8');
    process.stdout.write(`wrote ${dest} — ${out.length} lines\n`);
    return 0;
}

/**
 * Mirror `collections.Counter.most_common()` — descending count, ties broken by
 * insertion order (Python ≥3.7 Counter preserves first-seen order on equal
 * counts, and `most_common` is a stable sort by `-count`).
 */
function _mostCommon(counter: Map<string, number>): Array<[string, number]> {
    const items = [...counter.entries()];
    // Stable sort by descending count; ties keep insertion order.
    return items
        .map((e, i) => [e, i] as const)
        .sort((a, b) => {
            if (b[0][1] !== a[0][1]) {
                return b[0][1] - a[0][1];
            }
            return a[1] - b[1];
        })
        .map(([e]) => e);
}

const _isCliEntry =
    process.argv[1] !== undefined &&
    import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href;
if (_isCliEntry || process.argv[1] === _HERE) {
    process.exitCode = main();
}
