#!/usr/bin/env node
/**
 * Generate `docs/command-flows.md` — the Flows primary view (road-to-6.1.0 Step 9).
 *
 * TypeScript twin of `src/scripts/generate_command_flows.py` (ADR-096 —
 * Python→TS migration, Phase 8 / Wave 8a). The CLI contract is mirrored
 * EXACTLY: same flag (`--check`), same exit codes, same stdout/stderr
 * split, same byte-identical generated `docs/command-flows.md`. WRITER —
 * the rendered markdown matches the Python output byte-for-byte. No
 * behaviour changes — latent bugs replicated.
 *
 * Turns the flat command list into a FLOW-organized view from two
 * validated sources:
 *
 * - `src/flows/surface-map.yaml` — the complete command→flow classification.
 * - `src/flows/<flow>.yaml` — the rich user-work flow definitions.
 *
 * Command titles + descriptions come from each command's
 * `src/domains/<pack>/**\/command.md` frontmatter.
 *
 * Usage:
 *     ./scripts-run src/scripts/generate_command_flows
 *     ./scripts-run src/scripts/generate_command_flows --check
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { parse as parseYaml } from 'yaml';

import { _iter_domains_commands } from './_lib/agent_src.js';

const _HERE = fileURLToPath(import.meta.url);
// src/scripts/generate_command_flows.ts → parents[2] is the repo root.
const ROOT = path.resolve(path.dirname(_HERE), '..', '..');
const SURFACE_MAP = path.join(ROOT, 'src', 'flows', 'surface-map.yaml');
const FLOWS_DIR = path.join(ROOT, 'src', 'flows');
const OUT = path.join(ROOT, 'docs', 'command-flows.md');

type Dict = Record<string, unknown>;

// Python: re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL).match(text)
const FRONTMATTER_RE = /^---[^\S\n]*\n([\s\S]*?)\n---/;

function _frontmatter(p: string): Dict {
    const m = FRONTMATTER_RE.exec(fs.readFileSync(p, 'utf-8'));
    if (!m) {
        return {};
    }
    try {
        const parsed = parseYaml(m[1] as string, { version: '1.1' });
        return (parsed ?? {}) as Dict;
    } catch {
        return {};
    }
}

function _command_index(): Map<string, string> {
    const idx = new Map<string, string>();
    for (const [pathStr, logical] of _iter_domains_commands()) {
        // logical[len("commands/") : -len(".md")]
        const key = logical.slice('commands/'.length, logical.length - '.md'.length);
        idx.set(key, pathStr);
    }
    return idx;
}

// Human-facing section order + headings.
const USER_WORK = ['discovery', 'implementation', 'review', 'delivery'];
const SURFACE_HEADINGS: Record<string, [string, string]> = {
    product: [
        'Product-surface features',
        'Deliberately-started features — not daily flow members, never buried as skills.',
    ],
    'agent-admin': [
        'Platform surface — `agent-admin`',
        'The system/admin surface (NOT a flow): memory · analytics · governance · config · introspection, reached on demand.',
    ],
    media: ['Domain flow — media', 'AI image + video pipeline.'],
    marketing: ['Domain flow — marketing', 'Ghostwriter + post-as voice pipeline.'],
    fun: ['Domain flow — fun', 'Recreational packs.'],
    session: ['Session surface', 'Handoff / status / mode — conversation lifecycle.'],
};

function _cmd_line(ref: string, idx: Map<string, string>): string {
    const p = idx.get(ref);
    const fm = p ? _frontmatter(p) : {};
    const name = _pyTruthy(fm.name) ? String(fm.name) : ref;
    let desc = _pyStrip(_pyTruthy(fm.description) ? String(fm.description) : '');
    desc = _reSubWhitespace(desc);
    if (_len(desc) > 110) {
        desc = _pyRstripWs(_pySlice(desc, 0, 107)) + '…';
    }
    return desc ? `- \`${name}\` — ${desc}` : `- \`${name}\``;
}

function _load_flow_yaml(flow: string): Dict {
    const f = path.join(FLOWS_DIR, `${flow}.yaml`);
    if (!_isFile(f)) {
        return {};
    }
    const parsed = parseYaml(fs.readFileSync(f, 'utf-8'), { version: '1.1' });
    return (parsed ?? {}) as Dict;
}

export function render(): string {
    const data = (parseYaml(fs.readFileSync(SURFACE_MAP, 'utf-8'), { version: '1.1' }) ??
        {}) as Dict;
    const buckets = (data.commands as Record<string, unknown> | undefined) ?? {};
    const idx = _command_index();

    const out: string[] = [];
    out.push('<!-- GENERATED by scripts/generate_command_flows.py — do not edit by hand. -->');
    out.push(
        '<!-- Source: src/flows/surface-map.yaml + src/flows/<flow>.yaml. Re-run: task generate-command-flows. -->',
    );
    out.push('');
    out.push('# Command flows — the primary view');
    out.push('');
    out.push(
        '> road-to-6.1.0 Step 9. Commands are **flow members**, not a flat list. ' +
            'The layered model is `Profile → Pack → Flow → Command → Skill → Rule`; ' +
            'this view answers *"what am I trying to do?"* before *"which command do I type?"*.',
    );
    out.push('');
    out.push(
        '> Every command is classified in `src/flows/surface-map.yaml` ' +
            '(coverage enforced by `scripts/lint_command_flow_coverage.py`). The four ' +
            'user-work flows carry rich definitions in `src/flows/<flow>.yaml`.',
    );
    out.push('');

    const bucketKeys = Object.keys(buckets);
    let total = 0;
    for (const v of Object.values(buckets)) {
        total += Array.isArray(v) ? v.length : 0;
    }
    out.push(
        `**${total} commands** across **${bucketKeys.length} surfaces** ` +
            `(${USER_WORK.length} user-work flows + ${bucketKeys.length - USER_WORK.length} platform/domain surfaces).`,
    );
    out.push('');

    // --- User-work flows ----------------------------------------------------
    out.push('## User-work flows');
    out.push('');
    out.push('The developer story: **discovery → implementation → review → delivery**.');
    out.push('');
    for (const flow of USER_WORK) {
        const fy = _load_flow_yaml(flow);
        const title = _pyGet(fy, 'title', _title(flow)) as string;
        const summary = _reSubWhitespace(_pyStrip(_pyTruthy(fy.summary) ? String(fy.summary) : ''));
        out.push(`### ${title}`);
        out.push('');
        if (summary) {
            out.push(`_${summary}_`);
            out.push('');
        }
        const eps = (_pyTruthy(fy.entry_points) ? fy.entry_points : []) as unknown[];
        const dp = (_pyTruthy(fy.default_path) ? fy.default_path : []) as unknown[];
        if (eps.length > 0) {
            out.push(`**Entry points:** ${eps.map((e) => `\`${String(e)}\``).join(' · ')}`);
            out.push('');
        }
        if (dp.length > 0) {
            out.push(`**Default path:** ${dp.map((e) => `\`${String(e)}\``).join(' → ')}`);
            out.push('');
        }
        const refs = (_pyTruthy((buckets as Dict)[flow]) ? (buckets as Dict)[flow] : []) as unknown[];
        for (const ref of refs.slice().map(String).sort(_cmpStr)) {
            out.push(_cmd_line(ref, idx));
        }
        out.push('');
    }

    // --- Platform + domain surfaces -----------------------------------------
    out.push('## Platform & domain surfaces');
    out.push('');
    for (const surface of ['product', 'agent-admin', 'media', 'marketing', 'fun', 'session']) {
        const refsRaw = (buckets as Dict)[surface];
        if (!_pyTruthy(refsRaw)) {
            continue;
        }
        const [heading, blurb] = SURFACE_HEADINGS[surface] ?? [_title(surface), ''];
        out.push(`### ${heading}`);
        out.push('');
        if (blurb) {
            out.push(`_${blurb}_`);
            out.push('');
        }
        const refs = (refsRaw as unknown[]).slice().map(String).sort(_cmpStr);
        for (const ref of refs) {
            out.push(_cmd_line(ref, idx));
        }
        out.push('');
    }

    return _pyRstripWs(out.join('\n')) + '\n';
}

export function main(argv: string[] = process.argv.slice(2)): number {
    const check = argv.includes('--check');

    const content = render();
    if (check) {
        const current = _isFile(OUT) ? fs.readFileSync(OUT, 'utf-8') : '';
        if (current !== content) {
            process.stderr.write(
                'generate_command_flows: docs/command-flows.md is stale — ' +
                    'run `python3 scripts/generate_command_flows.py`\n',
            );
            return 1;
        }
        process.stdout.write('generate_command_flows: OK — docs/command-flows.md up to date\n');
        return 0;
    }

    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    fs.writeFileSync(OUT, content, 'utf-8');
    process.stdout.write(
        `generate_command_flows: wrote ${_relativeToPosix(OUT, ROOT)}\n`,
    );
    return 0;
}

// --- helpers -----------------------------------------------------------------

function _isFile(p: string): boolean {
    try {
        return fs.statSync(p).isFile();
    } catch {
        return false;
    }
}

function _pyTruthy(value: unknown): boolean {
    if (value === null || value === undefined) return false;
    if (typeof value === 'boolean') return value;
    if (typeof value === 'number') return value !== 0;
    if (typeof value === 'string') return value.length > 0;
    if (Array.isArray(value)) return value.length > 0;
    if (typeof value === 'object') return Object.keys(value).length > 0;
    return true;
}

/** Python dict.get(key, default): present key wins even if value is falsy. */
function _pyGet(d: Dict, key: string, dflt: unknown): unknown {
    return key in d ? d[key] : dflt;
}

/** Python `flow.title()` — title-case each word. */
function _title(s: string): string {
    return s.replace(/[A-Za-z]+/g, (w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase());
}

/** Python str.strip() (default whitespace cohort). */
const _PY_WS = [
    0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x1c, 0x1d, 0x1e, 0x1f, 0x20, 0x85, 0xa0, 0x1680, 0x2000,
    0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007, 0x2008, 0x2009, 0x200a, 0x2028,
    0x2029, 0x202f, 0x205f, 0x3000,
];

function _isPyWs(cp: number | undefined): boolean {
    return cp !== undefined && _PY_WS.includes(cp);
}

function _pyStrip(s: string): string {
    return _pyLstripWs(_pyRstripWs(s));
}

function _pyLstripWs(s: string): string {
    let start = 0;
    while (start < s.length && _isPyWs(s.codePointAt(start))) start += 1;
    return s.slice(start);
}

function _pyRstripWs(s: string): string {
    let end = s.length;
    while (end > 0 && _isPyWs(s.codePointAt(end - 1))) end -= 1;
    return s.slice(0, end);
}

/** Python re.sub(r"\s+", " ", text). Python's \s = [ \t\n\r\f\v] under str. */
function _reSubWhitespace(text: string): string {
    return text.replace(/[ \t\n\r\f\v]+/g, ' ');
}

/** Code-point length (Python len). */
function _len(s: string): number {
    let n = 0;
    for (const _c of s) n += 1;
    return n;
}

/** Python slicing s[a:b] on code points. */
function _pySlice(s: string, a: number, b: number): string {
    return [...s].slice(a, b).join('');
}

function _relativeToPosix(child: string, root: string): string {
    return path.relative(root, child).split(path.sep).join('/');
}

function _cmpStr(a: string, b: string): number {
    if (a < b) return -1;
    if (a > b) return 1;
    return 0;
}

const _isCliEntry =
    process.argv[1] !== undefined &&
    import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href;
if (_isCliEntry || process.argv[1] === _HERE) {
    process.exit(main());
}
