#!/usr/bin/env tsx
/**
 * Generate `agents/knowledge/INDEX.md` — the one-line catalog over every
 * knowledge surface: the flat anti-hallucination cards (ADR-100) plus the
 * lifecycle-typed sibling directories (`sessions/`, `concepts/`,
 * `procedures/`, `decisions/`) added by road-to-knowledge-system.
 *
 * Design per the 2026-07-05 council verdict (Option C — extend
 * `agents/knowledge/` in place): ONE index, index-first + grep retrieval,
 * no search infrastructure. This script is the deterministic backstop —
 * agents read INDEX.md first, grep second, read specific files third.
 *
 * Deterministic and idempotent: same inputs always produce byte-identical
 * output. No network, no LLM calls.
 *
 * Usage:
 *   generate_knowledge_index.ts [--dir <repo-root>] [--check] [--quiet]
 *
 * Exit codes: 0 = written / no drift, 1 = drift found (--check) or usage
 * error, 3 = internal error.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import YAML from 'yaml';

const _HERE = fileURLToPath(import.meta.url);
const PROG = 'generate_knowledge_index.ts';

const FRONTMATTER_RE = /^---[ \t]*\r?\n([\s\S]*?)\r?\n---[ \t]*\r?\n/;

// Section order is fixed — cards first (the pre-existing anti-hallucination
// store), then the lifecycle-typed dirs in capture-order (episodic → semantic
// → procedural → decisions).
const SECTIONS: ReadonlyArray<{ heading: string; dir: string | null }> = [
    { heading: 'Knowledge Cards', dir: null }, // flat *.md directly under agents/knowledge/
    { heading: 'Sessions', dir: 'sessions' },
    { heading: 'Concepts', dir: 'concepts' },
    { heading: 'Procedures', dir: 'procedures' },
    { heading: 'Decisions', dir: 'decisions' },
];

const SKIP_FILES = new Set(['README.md', 'INDEX.md']);
const MAX_SUMMARY_CHARS = 140;

interface Entry {
    file: string; // basename, e.g. "stripe-webhooks.md"
    relPath: string; // path relative to agents/knowledge/, POSIX separators
    summary: string;
}

function readFrontmatter(body: string): Record<string, unknown> {
    const m = FRONTMATTER_RE.exec(body);
    if (!m) return {};
    try {
        const parsed = YAML.parse(m[1]);
        return parsed && typeof parsed === 'object' ? (parsed as Record<string, unknown>) : {};
    } catch {
        return {};
    }
}

function stripFrontmatter(body: string): string {
    return body.replace(FRONTMATTER_RE, '');
}

function firstHeadingOrLine(body: string): string {
    for (const line of body.split(/\r?\n/)) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        return trimmed.replace(/^#+\s*/, '');
    }
    return '';
}

function truncate(s: string, max: number): string {
    if (s.length <= max) return s;
    return s.slice(0, max - 1).trimEnd() + '…';
}

/** Derive a one-line summary: frontmatter `description`/`summary` wins; else the first heading/line after frontmatter. */
function summarize(body: string): string {
    const fm = readFrontmatter(body);
    const fromFrontmatter = (fm.description ?? fm.summary) as unknown;
    if (typeof fromFrontmatter === 'string' && fromFrontmatter.trim()) {
        return truncate(fromFrontmatter.trim(), MAX_SUMMARY_CHARS);
    }
    const rest = stripFrontmatter(body);
    return truncate(firstHeadingOrLine(rest), MAX_SUMMARY_CHARS);
}

function listMarkdownFiles(dirPath: string): string[] {
    let entries: fs.Dirent[];
    try {
        entries = fs.readdirSync(dirPath, { withFileTypes: true });
    } catch {
        return [];
    }
    return entries
        .filter((e) => e.isFile() && e.name.toLowerCase().endsWith('.md') && !SKIP_FILES.has(e.name))
        .map((e) => e.name)
        .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

function collectSection(knowledgeRoot: string, dir: string | null): Entry[] {
    const scanDir = dir ? path.join(knowledgeRoot, dir) : knowledgeRoot;
    const files = listMarkdownFiles(scanDir);
    const out: Entry[] = [];
    for (const file of files) {
        const abs = path.join(scanDir, file);
        let body = '';
        try {
            body = fs.readFileSync(abs, 'utf8');
        } catch {
            continue;
        }
        const relPath = dir ? `${dir}/${file}` : file;
        out.push({ file, relPath, summary: summarize(body) });
    }
    return out;
}

function renderIndex(knowledgeRoot: string): string {
    const lines: string[] = [];
    lines.push('# Knowledge Index');
    lines.push('');
    lines.push(
        '_Auto-generated by `src/scripts/generate_knowledge_index.ts` — do not edit by hand. Regenerate with `task generate-knowledge-index`._',
    );
    lines.push('');
    lines.push(
        '_Retrieval protocol: read this index first, `grep` for keywords second, read the specific file third. Never enumerate every knowledge file directly._',
    );

    for (const section of SECTIONS) {
        const entries = collectSection(knowledgeRoot, section.dir);
        if (entries.length === 0) continue;
        lines.push('');
        lines.push(`## ${section.heading}`);
        lines.push('');
        for (const e of entries) {
            const title = e.file.replace(/\.md$/, '');
            const suffix = e.summary ? ` — ${e.summary}` : '';
            lines.push(`- [${title}](${e.relPath})${suffix}`);
        }
    }
    lines.push('');
    return lines.join('\n');
}

function printUsage(): void {
    process.stdout.write(`usage: ${PROG} [--dir DIR] [--check] [--quiet]\n`);
}

export function main(argv: string[]): number {
    let dir = process.cwd();
    let check = false;
    let quiet = false;

    for (let i = 0; i < argv.length; i++) {
        const arg = argv[i];
        if (arg === '-h' || arg === '--help') {
            printUsage();
            return 0;
        } else if (arg === '--dir') {
            const value = argv[++i];
            if (!value) {
                process.stderr.write(`${PROG}: error: --dir requires a value\n`);
                return 1;
            }
            dir = value;
        } else if (arg === '--check') {
            check = true;
        } else if (arg === '--quiet') {
            quiet = true;
        } else {
            process.stderr.write(`${PROG}: error: unrecognized argument: ${arg}\n`);
            printUsage();
            return 1;
        }
    }

    const knowledgeRoot = path.join(dir, 'agents', 'knowledge');
    if (!fs.existsSync(knowledgeRoot)) {
        if (!quiet) {
            process.stdout.write(`${PROG}: ${knowledgeRoot} does not exist — nothing to index.\n`);
        }
        return 0;
    }

    const rendered = renderIndex(knowledgeRoot);
    const indexPath = path.join(knowledgeRoot, 'INDEX.md');
    const existing = fs.existsSync(indexPath) ? fs.readFileSync(indexPath, 'utf8') : null;

    if (check) {
        if (existing === rendered) {
            if (!quiet) process.stdout.write(`${PROG}: agents/knowledge/INDEX.md is up to date.\n`);
            return 0;
        }
        process.stderr.write(
            `${PROG}: agents/knowledge/INDEX.md is stale — run without --check to regenerate.\n`,
        );
        return 1;
    }

    if (existing === rendered) {
        if (!quiet) process.stdout.write(`${PROG}: agents/knowledge/INDEX.md already up to date.\n`);
        return 0;
    }

    fs.writeFileSync(indexPath, rendered, 'utf8');
    if (!quiet) process.stdout.write(`${PROG}: wrote agents/knowledge/INDEX.md\n`);
    return 0;
}

if (fileURLToPath(import.meta.url) === path.resolve(process.argv[1] ?? '')) {
    process.exit(main(process.argv.slice(2)));
}
