#!/usr/bin/env node
/**
 * lint_code_comments — the carrier `code-comment-discipline` and the
 * "Code comments English" clause of `language-and-tone` never had.
 *
 * Both rules existed and neither could fire on the thing they govern.
 * `language-and-tone` is a kernel rule and names one enforcer,
 * `check_md_language.ts`, which rejects every path that is not `.md`
 * (`check_md_language.ts:175`) — so the code clause carried an `enforced_by`
 * entry that structurally cannot see a source file. `code-comment-discipline`
 * is `type: auto` and matches PROMPT keywords, so a run that writes forty-five
 * files without the user typing "comment", "refactor" or "implement" never
 * loads it at all. Measured 2026-09-02 in a consumer repository: 40 of 45
 * changed source files carried German comment lines, one of them a 101-line
 * colour-analysis report inside a CSS file.
 *
 * Three classes, each keyed on STRUCTURE rather than on a judgement about
 * prose, because a gate that has to decide whether a comment is "useful" is a
 * gate nobody can predict:
 *
 *   1. `de-comment`      — a comment line carrying German. Two independent
 *                          signals: a German-specific character, or two or
 *                          more German function words on one line.
 *   2. `report-comment`  — a comment block shaped like an analysis report.
 *                          The five literal patterns are in REPORT_SIGNALS,
 *                          named there rather than quoted here so this header
 *                          does not trip its own gate. Length is deliberately
 *                          NOT a signal; a long comment can be one long WHY.
 *   3. `provenance-comment` — a comment explaining where the code came from:
 *                          a roadmap path, a phase-and-step citation, a
 *                          prototype or reference artefact path. Evidence
 *                          belongs in the roadmap that asked for it, and a
 *                          second copy in the source is the copy in the wrong
 *                          place.
 *
 * Escape, per line or per file:
 *   code-comment-allow <class> -- <reason>
 * A reason is mandatory; the bare marker does not suppress.
 *
 * Scope is the DIFF by default, so a pre-existing tree does not turn red.
 * `--paths` and `--root` exist for auditing a tree the gate does not own.
 *
 * Exit codes: 0 clean · 2 findings · 1 usage or internal error.
 */
import { spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const _HERE = fileURLToPath(import.meta.url);

/** Extensions whose comment syntax the line classifier understands. */
export const SCANNED_EXTENSIONS = new Set([
    '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
    '.css', '.scss', '.less',
    '.php', '.py', '.go', '.rs', '.java', '.kt', '.swift', '.rb',
    '.vue', '.svelte',
]);

/** Paths that are generated, vendored, or otherwise not authored here. */
const SKIP_SEGMENTS = ['node_modules/', 'dist/', 'build/', '.next/', 'vendor/', 'coverage/'];

/** Header markers that mark a whole file as machine-written. */
const GENERATED_MARKERS = [
    'generated by', 'auto-generated', 'autogenerated', '@generated',
    'do not edit', 'code generated by',
];

/**
 * A comment line, in the languages above.
 *
 * Deliberately line-shaped rather than a parser: a parser would be more
 * precise about a comment token inside a string literal, and would also be a
 * dependency and a second definition of "what is a comment" for every language
 * added later. The cost of the approximation is a false positive on a string
 * that begins a line with `//` or `*`, which the escape marker answers.
 */
const COMMENT_LINE = /^\s*(\/\/|\/\*|\*(?!\/)|\*\/|#(?!!)|--)/;

/** German-specific characters. `ß` and the umlauts appear in no English word. */
const DE_CHARS = /[äöüßÄÖÜ]/;

/**
 * German function words. Function words rather than nouns on purpose: a noun
 * list is endless and collides with identifiers, while the closed class of
 * articles, prepositions, conjunctions and auxiliaries is small, stable, and
 * almost impossible to hit twice on one line of English.
 *
 * `die`, `man`, `hat`, `war`, `bei`, `im`, `am`, `so`, `ist` are deliberately
 * ABSENT even though they are German: each is either an English word or a
 * common identifier fragment, and the two-hit threshold is not enough
 * protection when a single term is that ambiguous.
 */
const DE_WORDS = new RegExp(
    '\\b(' + [
        'der', 'das', 'dem', 'den', 'des',
        'und', 'oder', 'aber', 'sondern', 'denn',
        'nicht', 'kein', 'keine', 'keiner', 'keinen',
        'wird', 'werden', 'wurde', 'worden', 'sind', 'waren',
        'eine', 'einen', 'einem', 'einer', 'eines',
        'dass', 'weil', 'damit', 'wenn', 'dann', 'sonst', 'obwohl',
        'hier', 'dort', 'oben', 'unten', 'auch', 'nur', 'schon', 'noch',
        'aus', 'fuer', 'ueber', 'durch', 'gegen', 'ohne', 'nach', 'vor',
        'beim', 'zum', 'zur', 'vom', 'mit', 'sich', 'ihre', 'ihrer', 'seine',
        'jede', 'jeder', 'jedes', 'alle', 'allen', 'aller',
        'diese', 'dieser', 'dieses', 'diesem',
        'steht', 'stehen', 'haben', 'kann', 'koennen', 'muss', 'muessen',
        'soll', 'sollte', 'gibt', 'geht', 'macht', 'zeigt', 'liegt',
        'deshalb', 'deswegen', 'trotzdem', 'bereits', 'immer', 'niemals',
        'warum', 'wieso', 'welche', 'welcher', 'wobei', 'sowie',
    ].join('|') + ')\\b',
    'gi',
);

/** Structural report markers — a comment shaped like a document, not a note. */
const REPORT_SIGNALS: ReadonlyArray<readonly [string, RegExp]> = [
    ['markdown-table', /^\s*(?:\/\/|\*|#|--)?\s*\|[^|]*\|[^|]*\|/],
    ['box-rule', /[─═━]{10,}/],
    ['section-mark', /^\s*(?:\/\/|\*|#|--)?\s*§\s+\S/],
    ['markdown-heading', /^\s*(?:\/\/|\*|#|--)?\s*#{2,}\s+\S/],
    ['revisit-if', /\brevisit-if\b/i],
];

/** Provenance markers — the code explaining its own paper trail. */
const PROVENANCE_SIGNALS: ReadonlyArray<readonly [string, RegExp]> = [
    ['roadmap-path', /\bagents\/roadmaps?\//i],
    ['reference-path', /\bagents\/(references|evidence|decisions)\//i],
    ['phase-step', /\b(phase|phase)\s*\d+\s*,\s*(step|schritt)\s*\d+/i],
    ['prototype-source', /\b(prototyp\w*|prototype)\b[^\n]{0,40}\.(html|fig|sketch|dc\.html)\b/i],
];

export type FindingClass = 'de-comment' | 'report-comment' | 'provenance-comment';

export interface CommentFinding {
    cls: FindingClass;
    file: string;
    line: number;
    signal: string;
    snippet: string;
}

/** An escape marker with a real reason, for `cls` or for every class. */
function escapedFor(line: string, cls: FindingClass): boolean {
    const m = /code-comment-allow\s+([a-z-]+|\*)\s*--\s*(\S.*)$/.exec(line);
    if (!m) return false;
    const target = m[1];
    return target === '*' || target === cls;
}

/** Is the whole file exempt — a file-level marker, or a generator header? */
export function fileIsExempt(text: string): boolean {
    const head = text.slice(0, 2000).toLowerCase();
    if (GENERATED_MARKERS.some((m) => head.includes(m))) return true;
    return /code-comment-allow-file\s*--\s*\S/.test(text.slice(0, 2000));
}

/** Strip the comment punctuation so a signal is matched against prose. */
function commentProse(line: string): string {
    return line.replace(/^\s*(\/\/+|\/\*+|\*+\/?|#+|--)/, ' ');
}

/**
 * Prose with code spans removed.
 *
 * The umlaut signal is otherwise wrong on an English docstring that quotes a
 * non-ASCII sample value — `café@exämple.com` in a scrubber's own
 * documentation is the measured case, and it is data being illustrated rather
 * than German being written. Backtick spans and quoted literals are where
 * that data lives, so both come out before the character test.
 */
function prosePlain(line: string): string {
    return commentProse(line)
        .replace(/`[^`]*`/g, ' ')
        .replace(/'[^']*'/g, ' ')
        .replace(/"[^"]*"/g, ' ')
        .replace(/[\u201c\u201e][^\u201c\u201d\u201e]*[\u201d\u201c]/g, ' ')
        .replace(/[\u2018\u201a][^\u2018\u2019\u201a]*[\u2019\u2018]/g, ' ')
        .replace(/\u00bb[^\u00ab\u00bb]*\u00ab/g, ' ')
        // Whatever follows the last UNPAIRED quote mark opens a quotation that
        // continues on the next line, so it is quoted data too. Pairs are gone
        // by now; an odd mark left over is an opening one.
        .replace(/[\u201c\u201e"][^\u201c\u201d\u201e"]*$/, ' ');
}

/**
 * Scan one file's text. Pure, so it answers for a buffer that is not on disk —
 * which is what the write-time hook needs.
 */
export function scanText(file: string, text: string): CommentFinding[] {
    if (fileIsExempt(text)) return [];
    const out: CommentFinding[] = [];
    const lines = text.split('\n');
    // A quotation that spans lines is the normal way this tree records what a
    // user actually said, and a per-line quote strip cannot see it: the
    // opening mark is on one line and the closing mark two lines down, so
    // every line between them reads as unquoted German. Carrying the open
    // state across the block is what separates quoted DATA from German PROSE,
    // and without it the six multi-line user quotations in this repository's
    // own hooks are false positives.
    let inQuote = false;

    for (let i = 0; i < lines.length; i++) {
        const raw = lines[i] ?? '';
        if (!COMMENT_LINE.test(raw)) { inQuote = false; continue; }
        const prose = commentProse(raw);
        const opensBefore = inQuote;
        const marks = (commentProse(raw).match(/[\u201c\u201d\u201e"]/g) ?? []).length;
        if (marks % 2 === 1) inQuote = !inQuote;
        if (opensBefore) continue;
        const at = i + 1;
        const snip = raw.trim().slice(0, 100);

        if (!escapedFor(raw, 'de-comment')) {
            const plain = prosePlain(raw);
            const distinct = new Set((plain.match(DE_WORDS) ?? []).map((h) => h.toLowerCase()));
            const umlaut = DE_CHARS.test(plain);
            // An umlaut ALONE proves nothing: `Robertson-Spärck-Jones`, a `Ü2`
            // step label and a quoted sample value all carry one while the
            // sentence around them is English. Two function words carry the
            // sentence on their own; one is enough once a German character is
            // also present. Measured over this repository's own source, both
            // thresholds together leave zero findings on 402 files.
            const isGerman = distinct.size >= 2 || (umlaut && distinct.size >= 1);
            if (isGerman) {
                out.push({
                    cls: 'de-comment', file, line: at,
                    signal: umlaut ? `umlaut+${[...distinct][0]}` : `function-words: ${[...distinct].slice(0, 4).join(' ')}`,
                    snippet: snip,
                });
            }
        }

        if (!escapedFor(raw, 'report-comment')) {
            for (const [name, re] of REPORT_SIGNALS) {
                if (re.test(raw)) {
                    out.push({ cls: 'report-comment', file, line: at, signal: name, snippet: snip });
                    break;
                }
            }
        }

        if (!escapedFor(raw, 'provenance-comment')) {
            for (const [name, re] of PROVENANCE_SIGNALS) {
                if (re.test(prose)) {
                    out.push({ cls: 'provenance-comment', file, line: at, signal: name, snippet: snip });
                    break;
                }
            }
        }
    }
    return out;
}

/** Should this path be scanned at all? */
export function isScannable(rel: string): boolean {
    if (SKIP_SEGMENTS.some((s) => rel.includes(s))) return false;
    if (rel.endsWith('.d.ts')) return false;
    return SCANNED_EXTENSIONS.has(path.extname(rel));
}

function changedFiles(root: string, base: string): string[] {
    const r = spawnSync('git', ['diff', '--name-only', '--diff-filter=ACMR', `${base}...HEAD`], {
        cwd: root, encoding: 'utf-8',
    });
    const tracked = r.status === 0 ? r.stdout.split('\n') : [];
    const u = spawnSync('git', ['ls-files', '--others', '--exclude-standard'], {
        cwd: root, encoding: 'utf-8',
    });
    const untracked = u.status === 0 ? u.stdout.split('\n') : [];
    const m = spawnSync('git', ['diff', '--name-only', '--diff-filter=ACMR'], {
        cwd: root, encoding: 'utf-8',
    });
    const dirty = m.status === 0 ? m.stdout.split('\n') : [];
    return [...new Set([...tracked, ...untracked, ...dirty])].filter((f) => f.trim().length > 0);
}

const HELP = `usage: lint_code_comments [--base <ref>] [--root <dir>] [--paths <f> …] [--report]

  --base <ref>   diff against this ref (default: origin/main)
  --root <dir>   run against another checkout (default: this repository)
  --paths        scan exactly these files, ignoring the diff
  --report       print every finding grouped by file and exit 0

Classes: de-comment · report-comment · provenance-comment
Escape:  code-comment-allow <class|*> -- <reason>   (per line)
         code-comment-allow-file -- <reason>        (first 2000 chars)
`;

export function main(argv: string[]): number {
    let base = 'origin/main';
    let root = path.resolve(path.dirname(_HERE), '..', '..');
    let reportOnly = false;
    const explicit: string[] = [];

    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--help' || a === '-h') { process.stdout.write(HELP); return 0; }
        else if (a === '--base') { base = argv[++i] ?? ''; }
        else if (a === '--root') { root = path.resolve(argv[++i] ?? '.'); }
        else if (a === '--report') { reportOnly = true; }
        else if (a === '--paths') { while (i + 1 < argv.length && !argv[i + 1]!.startsWith('--')) explicit.push(argv[++i]!); }
        else { process.stderr.write(`lint_code_comments: unknown argument ${a}\n${HELP}`); return 1; }
    }
    if (!base && explicit.length === 0) { process.stderr.write('--base needs a ref\n'); return 1; }

    const candidates = (explicit.length > 0 ? explicit : changedFiles(root, base)).filter(isScannable);
    const findings: CommentFinding[] = [];
    for (const rel of candidates) {
        const abs = path.isAbsolute(rel) ? rel : path.join(root, rel);
        let text: string;
        try { text = fs.readFileSync(abs, 'utf-8'); } catch { continue; }
        findings.push(...scanText(rel, text));
    }

    process.stdout.write(`scanned: ${candidates.length} source file(s) against ${explicit.length > 0 ? 'an explicit path list' : base}\n`);
    if (findings.length === 0) {
        process.stdout.write('✅  lint_code_comments: no German, report-shaped or provenance comments.\n');
        return 0;
    }

    const byFile = new Map<string, CommentFinding[]>();
    for (const f of findings) { const l = byFile.get(f.file) ?? []; l.push(f); byFile.set(f.file, l); }
    for (const [file, list] of [...byFile].sort()) {
        process.stdout.write(`\n${file}  (${list.length})\n`);
        for (const f of list.slice(0, 8)) {
            process.stdout.write(`  ${String(f.line).padStart(5)}  ${f.cls}/${f.signal}  ${f.snippet}\n`);
        }
        if (list.length > 8) process.stdout.write(`  … ${list.length - 8} more in this file\n`);
    }
    const counts = new Map<string, number>();
    for (const f of findings) counts.set(f.cls, (counts.get(f.cls) ?? 0) + 1);
    process.stdout.write(`\n${[...counts].map(([c, n]) => `${c}: ${n}`).join(' · ')} across ${byFile.size} file(s)\n`);

    if (reportOnly) return 0;
    process.stderr.write(
        '\n❌  lint_code_comments: comments carry language, evidence or report structure that does not belong in source.\n' +
        '    A comment states a WHY or a constraint the code cannot show, in English. Evidence belongs in the\n' +
        '    roadmap that asked for it. Rewrite the comment, delete it, or escape one line with\n' +
        '    `code-comment-allow <class> -- <reason>`.\n',
    );
    return 2;
}

const _isMain = (() => {
    const entry = process.argv[1];
    if (!entry) return false;
    try { return fs.realpathSync(entry) === fs.realpathSync(_HERE); } catch { return false; }
})();

if (_isMain) process.exit(main(process.argv.slice(2)));
