#!/usr/bin/env tsx
/**
 * The per-host injection-effect census — one line per host, provenance or none.
 *
 * `road-to-delivery-on-hook-hosts` steps 1.2 and 1.3. It renders the committed
 * record at `src/config/host-injection-effect.json` and adds the one thing the
 * record deliberately does not hold: the COMPUTED half, read fresh from the hook
 * manifest, so a reader sees both axes side by side and can see that they
 * disagree.
 *
 * WHY BOTH COLUMNS ARE PRINTED, ALWAYS
 * ------------------------------------
 * `cowork` is the row that makes this table worth generating: eight slots bound
 * and a measured `observed-false`. Printing only the observation would hide the
 * near-miss; printing only the binding would produce the wrong verdict for the
 * one host we have actually measured. The table exists so the gap between "could
 * emit" and "did arrive" is visible per host rather than argued in prose.
 *
 * It computes NO verdict. `admissibleUnderE3` is a one-line read of the observed
 * column and is applied by the caller that would change a projection, never here:
 * a report that also decided admission would be the single place where an
 * inference could quietly replace an observation.
 *
 * Usage:
 *     ./scripts-run src/scripts/report_host_injection_effect
 *     ./scripts-run src/scripts/report_host_injection_effect --emit --pin <sha>
 *
 * Deterministic: hosts sort by id, no timestamp, the pin is an argument.
 */

import { execFileSync, spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import {
    concernBound,
    loadRecord,
    recordProblems,
    type InjectionRecord,
} from './_lib/injection_effect.js';

const _HERE = fileURLToPath(import.meta.url);
export const REPO_ROOT = path.resolve(path.dirname(_HERE), '..', '..');
export const ARTIFACT_REL = path.join(
    'agents', 'evidence', 'analysis', 'host-injection-effect-2026-09.md',
);

/** Platform → slot → concern ids, straight out of the manifest. */
export function loadPlatforms(root: string): Record<string, Record<string, string[]>> {
    const raw = fs.readFileSync(path.join(root, 'src', 'scripts', 'hook_manifest.yaml'), 'utf-8');
    const out = spawnSync(
        process.execPath,
        [
            '-e',
            'const y=require("js-yaml");let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{' +
                'const d=y.load(s);process.stdout.write(JSON.stringify(d.platforms||{}))})',
        ],
        { input: raw, encoding: 'utf-8', cwd: root, maxBuffer: 64 * 1024 * 1024 },
    );
    if (out.status !== 0 || !out.stdout) {
        throw new Error(`hook_manifest.yaml could not be parsed: ${out.stderr || 'no output'}`);
    }
    return JSON.parse(out.stdout) as Record<string, Record<string, string[]>>;
}

/**
 * Keys under a platform that are NOT lifecycle slots.
 *
 * `fallback_only` is a marker saying this package binds nothing here, and
 * counting it as a slot made copilot read 1 against the 0 that
 * `docs/enforcement-by-host.md` records — a one-row disagreement with the host
 * table for a nameable reason, which is the drift this repository gates
 * elsewhere. Caught by comparing the generated table against that doc rather
 * than by a test, so it is named here.
 */
const NON_SLOT_KEYS: ReadonlySet<string> = new Set(['fallback_only']);

/** Lifecycle slots bound for a host, on the host table's own definition. */
export function boundSlotCount(platforms: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>>, host: string): number {
    return Object.keys(platforms[host] ?? {}).filter((k) => !NON_SLOT_KEYS.has(k)).length;
}

/** Host ids that are real rows, in sort order. Underscore keys are annotations. */
export function hostIds(rec: InjectionRecord): string[] {
    return Object.keys(rec).filter((k) => !k.startsWith('_')).sort();
}

export function renderArtifact(root: string, pin: string): string {
    const rec = loadRecord(root);
    const platforms = loadPlatforms(root);
    const L: string[] = [];
    L.push('<!-- evidence-type: analysis -->');
    L.push('# Host injection effect — does a delivered rule body reach the model?');
    L.push('');
    L.push(`Pinned to commit \`${pin}\`. Generated by`);
    L.push(`\`./scripts-run src/scripts/report_host_injection_effect --emit --pin ${pin}\`.`);
    L.push('Observations come from `src/config/host-injection-effect.json`; the binding column is');
    L.push('read fresh from `src/scripts/hook_manifest.yaml` on every run.');
    L.push('');
    L.push('## The two columns, and why neither is the other');
    L.push('');
    L.push('**Slots bound** is computed and cheap. **Body reaches the model** is observed and');
    L.push('expensive, and owner ruling E3 admits a host to `lean_projection.hosts` on the second');
    L.push('only: one transcript in which a model visibly acts on a delivered body. Documentation');
    L.push('of a host\'s hook API is not admission.');
    L.push('');
    L.push('`cowork` is why the distinction is not pedantry: **eight slots bound, and measured');
    L.push('`observed-false`** — its trampoline discards dispatcher output and exits 0. A table');
    L.push('with only the binding column would admit it.');
    L.push('');
    L.push('## Per host');
    L.push('');
    L.push('| Host | Slots bound | `rule-inject` on `user_prompt_submit` | Body reaches the model | Citation |');
    L.push('|---|---:|:-:|---|---|');
    for (const host of hostIds(rec)) {
        const obs = rec[host];
        const slots = boundSlotCount(platforms, host);
        const bound = concernBound(platforms, host, 'user_prompt_submit', 'rule-inject');
        const cite =
            obs !== undefined && obs.transcript !== null && obs.date !== null
                ? `\`${obs.transcript}\` (${obs.date})`
                : '—';
        L.push(
            `| \`${host}\` | ${String(slots)} | ${bound ? 'yes' : 'no'} | \`${obs?.state ?? 'unobserved'}\` | ${cite} |`,
        );
    }
    L.push('');
    L.push('## Why each row reads as it does');
    L.push('');
    for (const host of hostIds(rec)) {
        L.push(`- **\`${host}\`** — ${rec[host]?.reason ?? 'no row'}`);
    }
    const mdTree = rec['_cursor_md_tree_loaded'];
    if (mdTree !== undefined) {
        L.push('');
        L.push('## `cursor.md_tree_loaded` (step 1.3)');
        L.push('');
        L.push(`\`cursor.md_tree_loaded: ${mdTree.state}\` — ${mdTree.reason}`);
    }
    L.push('');
    L.push('## What this census does NOT do');
    L.push('');
    L.push('It computes no verdict. Admission under E3 is a one-line read of the observed column');
    L.push('and is applied by whatever would change a projection, never here — a report that also');
    L.push('decided admission would be the one place an inference could quietly replace an');
    L.push('observation.');
    L.push('');
    L.push('`unobserved` is a RESULT, not a gap: the host keeps its full rule bodies and loses');
    L.push('nothing while it waits, which is the roadmap\'s K6 and is asserted per PR by');
    L.push('`check_host_tree_parity` in the predecessor.');
    L.push('');
    return L.join('\n');
}

function headSha(root: string): string {
    return execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf-8' }).trim();
}

export function main(argv: readonly string[]): number {
    const root = REPO_ROOT;
    const rec = loadRecord(root);
    const problems = recordProblems(rec);
    if (problems.length > 0) {
        process.stderr.write('❌  the observation record is not admissible:\n');
        for (const p of problems) process.stderr.write(`  · ${p.host}: ${p.message}\n`);
        return 1;
    }
    const pinIdx = argv.indexOf('--pin');
    const pin = pinIdx !== -1 && pinIdx + 1 < argv.length ? (argv[pinIdx + 1] as string) : headSha(root);
    if (argv.includes('--emit')) {
        const out = path.join(root, ARTIFACT_REL);
        fs.mkdirSync(path.dirname(out), { recursive: true });
        fs.writeFileSync(out, renderArtifact(root, pin), 'utf-8');
        process.stdout.write(`wrote ${ARTIFACT_REL} · pin ${pin}\n`);
    }
    const hosts = hostIds(rec);
    const byState = new Map<string, number>();
    for (const h of hosts) byState.set(rec[h]!.state, (byState.get(rec[h]!.state) ?? 0) + 1);
    process.stdout.write(`scanned: ${String(hosts.length)} host(s)\n`);
    for (const [state, n] of [...byState].sort()) {
        process.stdout.write(`  ${state.padEnd(16)} ${String(n)}\n`);
    }
    return 0;
}

if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
    process.exit(main(process.argv.slice(2)));
}
