/**
 * Bundled content loader.
 *
 * The Worker bundle inlines `content.json` (uncompressed, schema_version 1)
 * at deploy time via `wrangler deploy`. R2 holds the gzipped archival copy
 * (Phase 3.4) but the Worker never fetches it at runtime — the bundle
 * IS the truth, per `mcp-cloud-scope.md` §3.3.
 *
 * The bundled JSON is generated by `scripts/pack_mcp_content.py` at
 * pipeline time. At Worker boot the content is validated once
 * (`assertManifest`) and frozen.
 */

import { assertManifest, type Manifest } from "./manifest.js";

export type PromptKind = "skill" | "command";
export type ResourceKind = "rule" | "guideline" | "context";
export type EntryKind = PromptKind | ResourceKind;

export type ContentEntry = {
  /** URI like `skill://verify-completion-evidence` or `rule://commit-policy`. */
  uri: string;
  /** Frontmatter `name:` value. */
  name: string;
  /** Frontmatter `description:` value or first-H1 fallback. */
  description: string;
  /** Body with frontmatter stripped. */
  body: string;
  /** `package` or `project` — from frontmatter `source:`. */
  source: string;
  kind: EntryKind;
  /** `text/markdown` for resources, omitted for prompts. */
  mime_type?: string;
};

export type ContentBlob = {
  schema_version: 1;
  uris: Record<string, ContentEntry>;
  manifest: Manifest;
};

/**
 * Validates a parsed JSON blob is a well-formed v1 ContentBlob. Throws on
 * mismatch — boot-time refusal is preferred to per-request failure.
 */
export function assertContentBlob(value: unknown): asserts value is ContentBlob {
  if (typeof value !== "object" || value === null) {
    throw new Error("content: not an object");
  }
  const b = value as Partial<ContentBlob>;
  if (b.schema_version !== 1) {
    throw new Error(
      `content: unsupported schema_version=${String(b.schema_version)}; expected 1`,
    );
  }
  if (typeof b.uris !== "object" || b.uris === null) {
    throw new Error("content: 'uris' must be an object");
  }
  if (typeof b.manifest !== "object" || b.manifest === null) {
    throw new Error("content: 'manifest' missing");
  }
  assertManifest(b.manifest);
}

/**
 * Filters entries by URI scheme. Used by `prompts/list` (skill, command)
 * and `resources/list` (rule, guideline, context).
 */
export function entriesOfKind(blob: ContentBlob, kinds: readonly EntryKind[]): ContentEntry[] {
  const set = new Set<EntryKind>(kinds);
  return Object.values(blob.uris).filter((e) => set.has(e.kind));
}

/**
 * Stub blob used by dev / tests when no packed content is present. The
 * production bundle replaces this via the build step (Phase 3.3).
 * Signature `0`*12 makes it obvious in logs that this is a placeholder.
 */
export const STUB_BLOB: ContentBlob = {
  schema_version: 1,
  uris: {},
  manifest: {
    schema_version: 1,
    signature: "000000000000",
    content_hash_sha256:
      "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    package_version: "0.0.0-dev",
    release_key: "v0.0.0-dev",
    git_sha: "0000000000000000000000000000000000000000",
    built_at: "1970-01-01T00:00:00Z",
    packer_version: "0.0.0",
    content_uri_count: { skill: 0, command: 0, rule: 0, guideline: 0, context: 0 },
  },
};
