"""Tests for ``scripts/_cli/cmd_migrate``.

P3.6 of road-to-portable-runtime-and-update-check.md. Covers:

- ``already migrated`` short-circuit on a clean repo.
- ``--dry-run`` detects legacy install without writing.
- npm devDependency entry stripped, package.json formatting preserved
  (no other keys lost).
- composer require entry stripped, composer.json formatting preserved.
- Legacy symlinks (pointing at ``vendor/`` or ``node_modules/``) are
  removed; user-managed symlinks elsewhere are preserved and reported.
- ``.agent-settings.yml`` is written with the running pin only when
  missing — never overwritten.
- ``.gitignore`` block is created / refreshed without losing other
  user-added entries.
- Re-running on an already-migrated repo is a no-op.
"""
from __future__ import annotations

import io
import json
import os
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scripts._cli import cmd_migrate as m  # noqa: E402


def _run(argv, project, *, version="1.42.0", out=None):
    out = out or io.StringIO()
    rc = m.main(argv, cwd=project, version=version, out=out)
    return rc, out.getvalue()


def _make_legacy_npm(project: Path) -> None:
    (project / "package.json").write_text(
        json.dumps(
            {
                "name": "consumer-app",
                "version": "0.1.0",
                "devDependencies": {
                    "@event4u/agent-config": "^1.0.0",
                    "other-dep": "1.2.3",
                },
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def _make_legacy_composer(project: Path) -> None:
    (project / "composer.json").write_text(
        json.dumps(
            {
                "name": "consumer/app",
                "require": {"event4u/agent-config": "^1.0", "psr/log": "^3.0"},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def test_clean_repo_already_migrated(tmp_path):
    rc, stdout = _run([], tmp_path)
    assert rc == 0
    assert "already migrated" in stdout


def test_dry_run_reports_without_writing(tmp_path):
    _make_legacy_npm(tmp_path)
    before = (tmp_path / "package.json").read_text(encoding="utf-8")
    rc, stdout = _run(["--dry-run"], tmp_path)
    assert rc == 0
    assert "legacy install detected" in stdout
    assert (tmp_path / "package.json").read_text(encoding="utf-8") == before


def test_strips_npm_devdependency(tmp_path):
    _make_legacy_npm(tmp_path)
    rc, _ = _run([], tmp_path)
    assert rc == 0
    data = json.loads((tmp_path / "package.json").read_text(encoding="utf-8"))
    assert "devDependencies" in data
    assert "@event4u/agent-config" not in data["devDependencies"]
    assert data["devDependencies"]["other-dep"] == "1.2.3"
    assert data["name"] == "consumer-app"


def test_strips_composer_require(tmp_path):
    _make_legacy_composer(tmp_path)
    rc, _ = _run([], tmp_path)
    assert rc == 0
    data = json.loads((tmp_path / "composer.json").read_text(encoding="utf-8"))
    assert "event4u/agent-config" not in data["require"]
    assert data["require"]["psr/log"] == "^3.0"
    assert data["name"] == "consumer/app"


def test_removes_legacy_symlinks(tmp_path):
    _make_legacy_npm(tmp_path)
    target = tmp_path / "node_modules" / "@event4u" / "agent-config" / ".augment"
    target.mkdir(parents=True)
    os.symlink(target, tmp_path / ".augment")
    rc, stdout = _run([], tmp_path)
    assert rc == 0
    assert not (tmp_path / ".augment").exists()
    assert "removed legacy symlink .augment" in stdout


def test_preserves_user_symlink_elsewhere(tmp_path):
    _make_legacy_npm(tmp_path)
    user_target = tmp_path / "custom-dir"
    user_target.mkdir()
    os.symlink(user_target, tmp_path / ".cursor")
    rc, stdout = _run([], tmp_path)
    assert rc == 0
    assert (tmp_path / ".cursor").is_symlink()
    assert "preserved user-managed .cursor" in stdout


def test_writes_settings_when_missing(tmp_path):
    _make_legacy_npm(tmp_path)
    rc, _ = _run([], tmp_path, version="2.0.0")
    assert rc == 0
    body = (tmp_path / ".agent-settings.yml").read_text(encoding="utf-8")
    assert 'agent_config_version: "2.0.0"' in body
    assert "generated by `agent-config migrate`" in body


def test_does_not_overwrite_existing_settings(tmp_path):
    _make_legacy_npm(tmp_path)
    (tmp_path / ".agent-settings.yml").write_text(
        'agent_config_version: "1.0.0"\nuser_key: keep\n', encoding="utf-8"
    )
    rc, stdout = _run([], tmp_path)
    assert rc == 0
    body = (tmp_path / ".agent-settings.yml").read_text(encoding="utf-8")
    assert 'agent_config_version: "1.0.0"' in body
    assert "user_key: keep" in body
    assert ".agent-settings.yml written" not in stdout


def test_gitignore_block_created(tmp_path):
    _make_legacy_npm(tmp_path)
    rc, _ = _run([], tmp_path)
    assert rc == 0
    text = (tmp_path / ".gitignore").read_text(encoding="utf-8")
    assert m.GITIGNORE_BLOCK_START in text
    assert ".agent-settings.yml" in text
    assert m.GITIGNORE_BLOCK_END in text


def test_gitignore_block_refreshed_preserving_user_lines(tmp_path):
    _make_legacy_npm(tmp_path)
    (tmp_path / ".gitignore").write_text(
        "node_modules/\n"
        f"{m.GITIGNORE_BLOCK_START}\n"
        "old-stale-entry\n"
        f"{m.GITIGNORE_BLOCK_END}\n"
        "*.log\n",
        encoding="utf-8",
    )
    rc, _ = _run([], tmp_path)
    assert rc == 0
    text = (tmp_path / ".gitignore").read_text(encoding="utf-8")
    assert "node_modules/" in text
    assert "*.log" in text
    assert "old-stale-entry" not in text
    assert ".agent-settings.yml" in text


def test_idempotent_second_run(tmp_path):
    _make_legacy_npm(tmp_path)
    _run([], tmp_path)
    rc, stdout = _run([], tmp_path)
    assert rc == 0
    assert "already migrated" in stdout
