"""Smoke tests for the `markitdown` skill (uncompressed authoring layer).

The compressed projection lives in `.agent-src/skills/markitdown/SKILL.md`
and is regenerated by `task sync`; we exercise the authoring source so a
broken edit fails fast independent of the sync step.

Coverage:

* Frontmatter shape — name, tier, source, status, description budget.
* Required body sections — every Step from the procedure plus the
  Provenance pin.
* Reference resolution — every internal markdown link inside the skill
  resolves to a file or directory inside the repo.
* Smoke-test fixtures — the three local fixtures named by the skill
  (`sample.pdf` / `sample.docx` / `sample.pptx`) exist and have the
  expected magic bytes.
"""

from __future__ import annotations

import re
import zipfile
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
SKILL_PATH = REPO_ROOT / ".agent-src.uncompressed" / "skills" / "markitdown" / "SKILL.md"
FIXTURES_DIR = REPO_ROOT / "tests" / "fixtures" / "markitdown"

REQUIRED_SECTIONS = (
    "## When to use",
    "## Token-saving math",
    "## Procedure: markitdown",
    "### Step 0: Verify peer-side install",
    "### Step 1: Install recipes",
    "### Step 2: Four-layer defense",
    "### Step 3: Markdown-output-explosion mitigations",
    "### Step 4: Per-host MCP client wiring",
    "### Step 5: Treat output as untrusted user content",
    "### Step 6: Validate",
    "## Output format",
    "## Gotcha",
    "## Do NOT",
    "## Provenance",
)

LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+)\)")


def _load_skill() -> tuple[dict, str]:
    text = SKILL_PATH.read_text(encoding="utf-8")
    assert text.startswith("---\n"), "skill must start with YAML frontmatter"
    _, fm, body = text.split("---\n", 2)
    return yaml.safe_load(fm), body


def test_frontmatter_required_keys() -> None:
    fm, _ = _load_skill()
    assert fm["name"] == "markitdown"
    assert fm["tier"] == "senior"
    assert fm["source"] == "package"
    assert fm["status"] == "active"
    assert isinstance(fm["description"], str)


def test_description_within_budget() -> None:
    fm, _ = _load_skill()
    # Skill linter hard cap is 200 chars (road-to-governance-cleanup F6).
    assert len(fm["description"]) <= 200, (
        f"description is {len(fm['description'])} chars; cap is 200"
    )


def test_required_body_sections_present() -> None:
    _, body = _load_skill()
    missing = [section for section in REQUIRED_SECTIONS if section not in body]
    assert not missing, f"missing skill sections: {missing}"


def test_upstream_pin_in_body() -> None:
    """`last_verified_with` is not an allowed frontmatter key, so the pin
    is recorded inline at the top of the body and again under Provenance."""
    _, body = _load_skill()
    assert "markitdown-mcp@0.0.1a4" in body, "upstream pin missing from body"
    assert "Pinned upstream" in body, "upstream pin block missing"


def test_internal_links_resolve() -> None:
    _, body = _load_skill()
    repo_relative = SKILL_PATH.parent
    unresolved: list[str] = []
    for link in LINK_RE.findall(body):
        target = link.split("#", 1)[0].strip()
        if not target or target.startswith(("http://", "https://", "mailto:")):
            continue
        candidate = (repo_relative / target).resolve()
        if not candidate.exists():
            unresolved.append(link)
    assert not unresolved, f"unresolved internal links: {unresolved}"


def test_fixture_pdf_is_valid() -> None:
    pdf = FIXTURES_DIR / "sample.pdf"
    head = pdf.read_bytes()[:8]
    assert head.startswith(b"%PDF-"), f"sample.pdf has wrong magic: {head!r}"
    assert pdf.stat().st_size < 50 * 1024, "sample.pdf must stay tiny (<50 KB)"


def test_fixture_docx_is_valid_office_zip() -> None:
    docx = FIXTURES_DIR / "sample.docx"
    assert docx.stat().st_size < 50 * 1024, "sample.docx must stay tiny (<50 KB)"
    with zipfile.ZipFile(docx) as zf:
        names = set(zf.namelist())
    assert "[Content_Types].xml" in names
    assert "word/document.xml" in names


def test_fixture_pptx_is_valid_office_zip() -> None:
    pptx = FIXTURES_DIR / "sample.pptx"
    assert pptx.stat().st_size < 50 * 1024, "sample.pptx must stay tiny (<50 KB)"
    with zipfile.ZipFile(pptx) as zf:
        names = set(zf.namelist())
    assert "[Content_Types].xml" in names
    assert "ppt/presentation.xml" in names
    assert "ppt/slides/slide1.xml" in names


def test_no_forbidden_uri_schemes_documented() -> None:
    """Layer-1 of the four-layer defense forbids `http:` URIs and metadata
    services. The skill must explicitly say so somewhere in Step 2."""
    _, body = _load_skill()
    step2 = body.split("### Step 2:", 1)[1].split("### Step 3:", 1)[0]
    for needle in ("http:", "169.254", "metadata", "Refuse"):
        assert needle in step2, f"Step 2 missing reference to: {needle}"
