// Source-of-truth data for `../build_mcp_catalog.ts` (Phase 3 of
// road-to-credible-install — MCP hygiene: generated truth, honest stubs).
//
// `consumer_tool_catalog.json` used to be hand-maintained: every tool's
// name/description/input_schema had to be kept in sync by hand across the
// JSON file AND its real handler registration in `tools.ts`. The generator
// derives the JSON from two registries instead of a third hand-edited copy:
//
//   - Implemented tools — `ALLOWLIST` in `./tools.ts`. Name, description,
//     input_schema, and side_effect all live on the handler registration
//     itself; the generator reads them directly.
//   - Stub-only tools — `STUB_TOOLS` below. Catalog-listed discovery
//     placeholders with no wired handler (or, for `catalog_search` /
//     `catalog_inspect` / `catalog_load`, a handler that exists in
//     `catalog_tools.ts` but is deliberately not promoted into ALLOWLIST
//     yet — see the file header there). These have no other natural home
//     in the codebase, so their metadata is authored here.
//
// Never hand-edit `consumer_tool_catalog.json` — run
// `npm run build:mcp-catalog` (or `./scripts-run src/scripts/build_mcp_catalog
// --write`) after changing a tool's registration or a `STUB_TOOLS` entry.
import type { ToolSideEffect } from './tools.js';

export type { ToolSideEffect };

/** Free-text top-level `description` field. Human-facing only. */
export const CATALOG_DESCRIPTION =
    'Source-of-truth catalog of consumer-relevant MCP tools. Read by the ' +
    'stdio server (scripts/mcp_server/) and packed into the Cloud Worker ' +
    "bundle (internal/workers/mcp/). The 'implemented_on' field lists " +
    'transports where the real handler is wired. Entries marked ' +
    "'[stub — implemented on demand]' are DOCUMENTATION of the on-demand " +
    'backlog: per ADR-132 they are NOT registered on the stdio tools/list ' +
    "(the wire carries implemented tools only); the 'not_implemented' " +
    'envelope contract (docs/contracts/mcp-tool-stub-envelope.md) remains ' +
    'for Worker parity. Generated by `build_mcp_catalog` — ' +
    'never hand-edit this file.';

export interface StubToolSource {
    readonly name: string;
    readonly description: string;
    readonly side_effect: ToolSideEffect;
    readonly input_schema: Record<string, unknown>;
}

/**
 * Catalog-only tools with no wired ALLOWLIST handler. `implemented_on` is
 * always `[]` for these — the generator adds the `[stub — implemented on
 * demand]` description marker and omits `annotations` (no real behavior to
 * annotate).
 */
export const STUB_TOOLS: readonly StubToolSource[] = [
    {
        name: 'skill_trigger_eval',
        description:
            'Score a user message against the compiled router and return ' +
            'the skills whose triggers match, each with the reason it ' +
            'fired. Use to predict which skills a given message would ' +
            'activate, for debugging trigger coverage. Read-only and ' +
            'deterministic. Returns a ranked list of matching skills with ' +
            'their trigger reasons.',
        side_effect: 'ro',
        input_schema: {
            type: 'object',
            properties: {
                message: { type: 'string', description: 'The user message to score against skill triggers.' },
                context: { type: 'string', description: 'Optional recent-turn context to sharpen the match.' },
                limit: {
                    type: 'integer',
                    minimum: 1,
                    default: 5,
                    description: 'Maximum number of matching skills to return. Defaults to 5.',
                },
            },
            required: ['message'],
            additionalProperties: false,
        },
    },
    {
        name: 'suggest_command',
        description:
            'Run the command-suggestion engine: score the available slash ' +
            'commands against a user message and context, and return a ' +
            'ranked, numbered-options block of the best matches. Use to ' +
            'recommend a command for a free-form request without invoking ' +
            'anything. Read-only and deterministic. Returns the formatted ' +
            'suggestion block plus the scored candidates.',
        side_effect: 'ro',
        input_schema: {
            type: 'object',
            properties: {
                message: { type: 'string', description: 'The user message to match commands against.' },
                context: { type: 'string', description: 'Optional recent-turn context to sharpen the match.' },
            },
            required: ['message'],
            additionalProperties: false,
        },
    },
    // `suggest_skill_for_task` moved to ALLOWLIST in mcp_server/tools.ts
    // (road-to-inbox-harvest-2026-08-d-runtime-skill-routing 4.1) — it is
    // implemented now, and `build_mcp_catalog` refuses a name registered in
    // both places. Its published input schema (`task` + `limit`) was carried
    // over verbatim rather than re-designed: the stub is a contract consumers
    // may already have read.
    {
        name: 'mine_session',
        description:
            'Extract reusable patterns, decisions, and learnings from a ' +
            'single chat-history session, as candidate memory entries. Use ' +
            'to distill a finished session into durable memory before it ' +
            'ages out. Read-only. Returns the mined candidates grouped by ' +
            'kind.',
        side_effect: 'ro',
        input_schema: {
            type: 'object',
            properties: {
                session: { type: 'string', description: 'Session id to mine.' },
                path: {
                    type: 'string',
                    description: 'Optional path to a chat-history JSONL; defaults to the standard location.',
                },
            },
            additionalProperties: false,
        },
    },
    {
        name: 'update_form_request_messages',
        description:
            "Synchronise the `messages()` method of a Laravel FormRequest " +
            'class: add entries for validation rules that lack a custom ' +
            'message, link them to translation keys, and drop stale ones. ' +
            "Use after changing a FormRequest's `rules()`. Edits the class " +
            'file on disk and returns the planned or applied message ' +
            'changes. Set `dry_run: true` to preview the diff without ' +
            'writing.',
        side_effect: 'fs-write',
        input_schema: {
            type: 'object',
            properties: {
                request_class: {
                    type: 'string',
                    description: 'Fully-qualified FormRequest class FQN or repo-relative file path.',
                },
                dry_run: {
                    type: 'boolean',
                    default: false,
                    description: 'When true, return the planned message changes without editing the file.',
                },
            },
            required: ['request_class'],
            additionalProperties: false,
        },
    },
    {
        name: 'sync_gitignore',
        description:
            'Synchronise the managed `event4u/agent-config` block in the ' +
            "consumer project's `.gitignore` — add missing canonical " +
            'entries while preserving user-added lines. Use after ' +
            'upgrading the package or when generated paths are being ' +
            'tracked by mistake. Edits `.gitignore` and returns the added ' +
            '/ removed entries. Set `dry_run: true` to preview the changes.',
        side_effect: 'fs-write',
        input_schema: {
            type: 'object',
            properties: {
                dry_run: {
                    type: 'boolean',
                    default: false,
                    description: 'When true, return the planned `.gitignore` changes without writing the file.',
                },
            },
            additionalProperties: false,
        },
    },
    {
        name: 'sync_agent_settings',
        description:
            'Synchronise `.agent-settings.yml` against the current ' +
            'template and active profile — add new sections and keys ' +
            'while preserving existing user values. Use after a package ' +
            'upgrade to pick up newly introduced settings. Edits the ' +
            'settings file and returns the keys that were (or would be) ' +
            'added. Set `dry_run: true` to preview.',
        side_effect: 'fs-write',
        input_schema: {
            type: 'object',
            properties: {
                profile: { type: 'string', description: 'Override the profile pinned in the settings file.' },
                dry_run: {
                    type: 'boolean',
                    default: false,
                    description: 'When true, return the planned settings changes without writing the file.',
                },
            },
            additionalProperties: false,
        },
    },
    {
        name: 'run_quality_checks',
        description:
            "Run the consumer project's configured quality gate (PHPStan " +
            '/ Rector / ECS or the stack equivalent) and return a ' +
            'structured per-tool result. Use before committing to confirm ' +
            'static-analysis and style gates pass. Shell-bound. Pass ' +
            '`tool` to run a single gate; omit to run all.',
        side_effect: 'shell',
        input_schema: {
            type: 'object',
            properties: {
                tool: { type: 'string', description: 'Restrict to a single quality tool by name (e.g. phpstan, rector, ecs).' },
            },
            additionalProperties: false,
        },
    },
    {
        name: 'compile_router',
        description:
            'Regenerate the compiled router (`router.compiled.json`) from ' +
            'the current rule, skill, and command frontmatter, so ' +
            'trigger-based routing reflects the latest artifacts. Use ' +
            "after adding or editing a rule / skill / command's trigger " +
            'metadata. Shell-bound — wraps `scripts/compile_router.py` — ' +
            'and returns the regenerated router summary. Set `dry_run: ' +
            'true` to compute the result without writing the file.',
        side_effect: 'shell',
        input_schema: {
            type: 'object',
            properties: {
                dry_run: {
                    type: 'boolean',
                    default: false,
                    description: 'When true, compute the router without writing `router.compiled.json` to disk.',
                },
            },
            additionalProperties: false,
        },
    },
    {
        name: 'catalog_search',
        description:
            "Search the package's own artifact catalog (skills, personas, " +
            'commands) by free-text query and return ranked summaries — ' +
            'name, description, tags, score — WITHOUT loading any body. ' +
            'Use to discover which skill or persona fits a task when the ' +
            'full catalog is not in context. Read-only, deterministic ' +
            '(BM25 over an on-disk index). Activation deferred behind a ' +
            'task-quality A/B (see catalog_tools.ts).',
        side_effect: 'ro',
        input_schema: {
            type: 'object',
            properties: {
                query: { type: 'string', description: 'Free-text search query.' },
                class: {
                    type: 'string',
                    enum: ['skill', 'persona', 'command'],
                    description: 'Optional: restrict to one artifact class.',
                },
                pack: { type: 'string', description: 'Optional: restrict to entries tagged with this pack/domain.' },
                limit: {
                    type: 'integer',
                    minimum: 1,
                    default: 8,
                    description: 'Maximum results. Defaults to 8.',
                },
            },
            required: ['query'],
            additionalProperties: false,
        },
    },
    {
        name: 'catalog_inspect',
        description:
            'Return the metadata for one catalog entry by id (id, class, ' +
            'name, description, tags, path). Body is returned ONLY when ' +
            'include_body is true. Use after catalog_search to look at a ' +
            'candidate before loading it. Read-only. Activation deferred ' +
            '(see catalog_search).',
        side_effect: 'ro',
        input_schema: {
            type: 'object',
            properties: {
                id: { type: 'string', description: 'Catalog id, e.g. `skill:api-design` or `persona:backend-architect`.' },
                include_body: {
                    type: 'boolean',
                    default: false,
                    description: 'When true, include the full body. Defaults to false (metadata only).',
                },
            },
            required: ['id'],
            additionalProperties: false,
        },
    },
    {
        name: 'catalog_load',
        description:
            'Load the full body of one catalog entry by id, wrapped in a ' +
            "neutral reference preamble that subordinates it to the user's " +
            'request and system instructions. Use to bring a ' +
            'skill/persona/command body into context on demand. Read-only, ' +
            'path-confined to the package root. Never injects or acts — ' +
            'the host decides what to do with the body. Activation ' +
            'deferred (see catalog_search).',
        side_effect: 'ro',
        input_schema: {
            type: 'object',
            properties: {
                id: { type: 'string', description: 'Catalog id to load the body for.' },
            },
            required: ['id'],
            additionalProperties: false,
        },
    },
];
