#!/usr/bin/env bash
# agent-config — thin wrapper for the event4u/agent-config CLI.
#
# Auto-generated by the package installer. Delegates to the master CLI
# shipped inside the installed package (node_modules or vendor). Do NOT
# edit — this file is gitignored and regenerated on every install.
#
# Usage:
#   ./agent-config help
#   ./agent-config mcp:render
#   ./agent-config roadmap:progress
#
# See: https://github.com/event4u-app/agent-config

set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

locate_master() {
  local candidates=(
    "$SELF_DIR/node_modules/@event4u/agent-config/scripts/agent-config"
    "$SELF_DIR/vendor/event4u/agent-config/scripts/agent-config"
  )
  local c
  for c in "${candidates[@]}"; do
    if [[ -x "$c" ]]; then
      printf '%s' "$c"
      return 0
    fi
  done
  return 1
}

if ! MASTER="$(locate_master)"; then
  cat >&2 <<EOF
❌  agent-config: master CLI not found.
    Tried:
      - node_modules/@event4u/agent-config/scripts/agent-config
      - vendor/event4u/agent-config/scripts/agent-config
    Reinstall the package, then retry:
      npm install        # for Node projects
      composer install   # for PHP projects
EOF
  exit 127
fi

exec "$MASTER" "$@"
