#!/usr/bin/env python3
"""Generate ``pack.yaml`` + ``README.md`` for every ``packages/*/`` tree.

Phase 4.4 of the monorepo migration (ADR-017). The manifests are
*derived* from frontmatter + ``config/discovery/packs.yml``; they are
regenerated on every ``task sync`` and must never be hand-edited.

For each package directory under ``packages/`` we emit:
  - ``packages/<pkg>/pack.yaml`` — id, label, owner (workspaces),
    requires, version, artefact_count
  - ``packages/<pkg>/README.md`` — pack description + per-artefact
    description table

CLI:
  --check     exit non-zero if any output would change (CI gate)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _lib.agent_src import iter_all_sources  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
PACKAGES = ROOT / "packages"
PACKS_VOCAB = ROOT / "config" / "discovery" / "packs.yml"
PACKAGE_JSON = ROOT / "package.json"
GENERATED_HEADER = "# Generated by scripts/generate_pack_manifests.py — DO NOT EDIT BY HAND\n"


def _load_yaml(path: Path) -> Any:
    if not path.exists():
        return None
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _read_frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    try:
        data = yaml.safe_load(text[4:end])
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def _pack_id_from_dir(pkg_dir: Path) -> str:
    name = pkg_dir.name
    return "core" if name == "core" else name.removeprefix("pack-")


def _vocab_lookup(packs_vocab: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {p["id"]: p for p in (packs_vocab or [])}


def _package_version() -> str:
    if not PACKAGE_JSON.exists():
        return "0.0.0"
    return json.loads(PACKAGE_JSON.read_text(encoding="utf-8")).get("version", "0.0.0")


def _collect_artefacts(pkg_dir: Path) -> list[dict[str, Any]]:
    src_root = pkg_dir / ".agent-src.uncondensed"
    if not src_root.is_dir():
        return []
    items: list[dict[str, Any]] = []
    for p in sorted(src_root.rglob("*.md")):
        if not p.is_file():
            continue
        fm = _read_frontmatter(p)
        if not fm:
            continue
        items.append({
            "path": p.relative_to(src_root).as_posix(),
            "name": fm.get("name") or (p.parent.name if p.name == "SKILL.md" else p.stem),
            "description": (fm.get("description") or "").strip(),
            "category": _category_for(p, src_root),
            # Include edges — the skills / rules this artefact references in its
            # frontmatter. Drives the generated `dependencies` block + the
            # dependency lint (road-to-6.0.0-D Phase 0 Steps 2-3).
            "skills": [s for s in (fm.get("skills") or []) if isinstance(s, str)],
            "rules": [r for r in (fm.get("rules") or []) if isinstance(r, str)],
        })
    return items


def _category_for(path: Path, src_root: Path) -> str:
    rel = path.relative_to(src_root).as_posix()
    top = rel.split("/", 1)[0]
    mapping = {"skills": "skill", "rules": "rule", "commands": "command",
               "personas": "persona", "guidelines": "guideline",
               "contexts": "context", "presets": "preset", "profiles": "profile"}
    return mapping.get(top, top)


def _build_pack_yaml(pkg_dir: Path, vocab: dict[str, dict[str, Any]],
                     artefacts: list[dict[str, Any]], version: str) -> dict[str, Any]:
    pid = _pack_id_from_dir(pkg_dir)
    meta = vocab.get(pid) or {}
    label = meta.get("label") or (pid.title() if pid == "core" else pid)
    out: dict[str, Any] = {
        "id": pid,
        "label": label,
        "description": meta.get("description") or ("Core framework-neutral artefacts." if pid == "core" else ""),
        "owner": meta.get("workspaces") or (["agent-config-maintainer"] if pid == "core" else []),
        "requires": meta.get("requires") or meta.get("requires_hint") or [],
        "trust_level_default": meta.get("trust_level_default") or "core",
        "version": version,
        "artefact_count": len(artefacts),
    }
    if isinstance(meta.get("onboarding"), dict):
        out["onboarding"] = meta["onboarding"]
    # size_class / suggests come from the discovery vocab (config/discovery/packs.yml)
    # when defined there; the pack.yaml schema (scripts/schemas/pack.schema.json)
    # treats them as optional so reserved-vocab packs without artefacts still validate.
    if meta.get("size_class"):
        out["size_class"] = meta["size_class"]
    out["suggests"] = meta.get("suggests") or []
    # dependencies — the artefact-level include graph (skills / rules the pack's
    # commands reference). Generated from frontmatter so it stays in sync; the
    # dependency lint re-derives this and fails on drift, validate_pack_yaml.py
    # fails on a reference that no longer resolves (road-to-6.0.0-D Phase 0).
    dep_skills: set[str] = set()
    dep_rules: set[str] = set()
    for a in artefacts:
        dep_skills.update(a.get("skills") or [])
        dep_rules.update(a.get("rules") or [])
    out["dependencies"] = {
        "skills": sorted(dep_skills),
        "rules": sorted(dep_rules),
    }
    return out


def _render_readme(pack_meta: dict[str, Any], artefacts: list[dict[str, Any]]) -> str:
    lines = [GENERATED_HEADER, f"# {pack_meta['label']}", ""]
    if pack_meta.get("description"):
        lines += [pack_meta["description"], ""]
    lines += [f"- **id**: `{pack_meta['id']}`",
              f"- **version**: `{pack_meta['version']}`",
              f"- **owner**: {', '.join(pack_meta['owner']) or '—'}",
              f"- **requires**: {', '.join(pack_meta['requires']) or '—'}",
              f"- **artefacts**: {pack_meta['artefact_count']}", ""]
    by_cat: dict[str, list[dict[str, Any]]] = {}
    for a in artefacts:
        by_cat.setdefault(a["category"], []).append(a)
    for cat in sorted(by_cat):
        lines += [f"## {cat.title()}s ({len(by_cat[cat])})", ""]
        for a in sorted(by_cat[cat], key=lambda x: x["name"]):
            desc = a["description"] or "_(no description)_"
            lines.append(f"- **`{a['name']}`** — {desc}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _write_if_changed(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return False
    if check:
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit non-zero on drift")
    args = ap.parse_args()
    vocab = _vocab_lookup(_load_yaml(PACKS_VOCAB) or [])
    version = _package_version()
    if not PACKAGES.exists():
        print("packages/ does not exist — nothing to generate", file=sys.stderr)
        return 0
    drift = 0
    for pkg in sorted(PACKAGES.iterdir()):
        if not pkg.is_dir():
            continue
        artefacts = _collect_artefacts(pkg)
        meta = _build_pack_yaml(pkg, vocab, artefacts, version)
        yaml_body = GENERATED_HEADER + yaml.safe_dump(meta, sort_keys=True, allow_unicode=True)
        readme_body = _render_readme(meta, artefacts)
        if _write_if_changed(pkg / "pack.yaml", yaml_body, args.check):
            drift += 1
            print(f"{'drift' if args.check else 'wrote'}: {pkg.name}/pack.yaml")
        if _write_if_changed(pkg / "README.md", readme_body, args.check):
            drift += 1
            print(f"{'drift' if args.check else 'wrote'}: {pkg.name}/README.md")
    if args.check and drift:
        print(f"pack manifests out of date ({drift} file(s)) — run `task generate-pack-manifests`", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
