/**
 * The attribution line a generated artifact carries.
 *
 * `road-to-consumer-repo-reality` Phase 1, step 1.4: "A generated file that
 * names the script that wrote it becomes a lie the moment that script moves.
 * Emit a stable, resolvable reference instead."
 *
 * IT ALREADY HAPPENED, which is why this module exists rather than a style
 * note. Measured 2026-08-26 across `src/`, ten generated artifacts named their
 * generator by literal path and **six of those paths did not resolve**:
 *
 *   scripts/audit_user_type_axis.py   scripts/adoption_report.py
 *   scripts/skill_overlap.py          scripts/gen_discovery_baseline.py
 *   scripts/generate_ownership_matrix.py
 *   scripts/generate_pack_manifests.ts
 *
 * The first five were retired by the py2ts migration (ADR-200) and the sixth by
 * the `scripts/` → `src/scripts/` move. Each artifact kept telling its reader to
 * go look at a file that is not there — the same over-reporting failure Phase 1
 * measures in consumer root instruction files, produced by this package's own
 * generators.
 *
 * THE STABLE REFERENCE IS THE COMMAND, NOT THE PATH. A path is an
 * implementation detail that a refactor moves; the command a human runs to
 * regenerate is the thing that stays true, and it is also the only half of the
 * attribution a reader can act on. Where no command exists, the generator's
 * MODULE NAME is used — stable under a directory move, and greppable.
 */

/**
 * `Generated by <ref>. Do not edit.` — with `ref` a command or a module name,
 * never a path.
 *
 * @param ref     the regeneration command (`agent-config sync`, `task sync`) or
 *                the generator's module name (`regenerate_index`). A value
 *                containing a path separator is a bug this function refuses
 *                rather than emits, because emitting it is exactly the defect.
 * @param detail  optional trailing clause, e.g. a source description. No
 *                timestamp: a regenerated timestamp makes every run a diff.
 */
export function generatedBy(ref: string, detail?: string): string {
    if (ref.includes('/') || ref.includes('\\')) {
        throw new Error(
            `generatedBy: "${ref}" contains a path separator. The attribution must be a command or a ` +
                'module name — a literal path becomes wrong the moment the file moves, which is the ' +
                'defect this helper exists to prevent (road-to-consumer-repo-reality 1.4).',
        );
    }
    const tail = detail === undefined || detail.trim() === '' ? '' : ` ${detail.trim()}`;
    return `Generated by \`${ref}\`. Do not edit.${tail}`;
}

/** The same line as a markdown blockquote, the shape most emitters use. */
export function generatedByQuote(ref: string, detail?: string): string {
    return `> ${generatedBy(ref, detail)}`;
}

/** The same line as an italic footer, for artifacts that use one. */
export function generatedByItalic(ref: string, detail?: string): string {
    return `_${generatedBy(ref, detail)}_`;
}

/** The same line as a `#` comment, for YAML and INI-shaped output. */
export function generatedByComment(ref: string, detail?: string): string {
    return `# ${generatedBy(ref, detail)}`;
}
