// Adversarial precision/recall measurement for the secret detector
// (road-to-feedback-9.8.0-followups Phase 3). Runs the REAL scanText over
// the committed fixture corpus plus runtime-constructed multiline cases
// (assembled from parts so nothing key-shaped beyond the existing corpus
// convention lands in the tree), computes precision / recall / FP-rate, and
// publishes the rates to internal/reports/secret-scanner-adversarial.json.
//
// Hard floor: recall = 100% on positives, FP-rate = 0% on negative controls.
// A genuine detector miss must NOT be papered over by weakening a fixture —
// it gets a known_gap entry excluded from the hard assertion and REPORTED.
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { scanText, type SecretFinding } from './secret_detector.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.join(HERE, 'fixtures', 'secret-detector');
const REPO = path.resolve(HERE, '..', '..', '..');
const REPORT = path.join(REPO, 'internal', 'reports', 'secret-scanner-adversarial.json');

/** Measured, documented gaps — excluded from the hard floor, published. */
const KNOWN_GAPS: string[] = [];

const isReal = (f: SecretFinding): boolean => f.confidence === 'high' || f.confidence === 'medium';

interface Case { id: string; text: string; expect_hit: boolean }

function corpusCases(): Case[] {
    const cases: Case[] = [];
    for (const [file, expectHit] of [['positives.txt', true], ['negatives.txt', false]] as const) {
        const lines = fs.readFileSync(path.join(FIXTURES, file), 'utf-8').split('\n');
        lines.forEach((line, i) => {
            if (line.trim().length === 0 || line.startsWith('#')) return;
            const value = expectHit ? (line.split('|')[1] ?? line) : line;
            cases.push({ id: `${file}:${i + 1}`, text: value, expect_hit: expectHit });
        });
    }
    return cases;
}

/** Multiline / wrapped positives assembled at runtime. */
function constructedCases(): Case[] {
    // A fake PEM body: base64-ish filler between real BEGIN/END framing.
    const pem = [
        ['-----BEGIN', 'RSA PRIVATE KEY-----'].join(' '),
        'MIIEpAIBAAKCAQEA7fakebodyfakebodyfakebodyfakebodyfakebody12345678',
        'q7fakebodyfakebodyfakebodyfakebodyfakebodyfakebodyfakebody901234',
        ['-----END', 'RSA PRIVATE KEY-----'].join(' '),
    ].join('\n');
    // A base64-WRAPPED credential next to a keyword: the wrapped payload is a
    // fake AWS key; the wrapper alone must still trip entropy+keyword.
    const wrapped = `api_key = "${Buffer.from('AKIA' + '1234567890ABCDEF').toString('base64')}"`;
    // .env multiline block (several assignments in one scan call).
    const envBlock = ['APP_ENV=production', 'DB_PASSWORD=q7Xp2Vr9kLm4Nt8wYz3BdF6h', 'MAIL_FROM=noreply@example.com'].join('\n');
    return [
        { id: 'constructed:pem-multiline', text: pem, expect_hit: true },
        { id: 'constructed:base64-wrapped-key', text: wrapped, expect_hit: true },
        { id: 'constructed:env-block', text: envBlock, expect_hit: true },
        // Negative: random base64 with NO credential keyword nearby.
        { id: 'constructed:naked-base64-no-keyword-short', text: 'blob dGhpcyBpcyBmaWxsZXI=', expect_hit: false },
    ];
}

describe('secret detector — adversarial corpus measurement', () => {
    const cases = [...corpusCases(), ...constructedCases()];
    const rows = cases.map((c) => {
        const real = scanText(c.text).filter(isReal);
        return { ...c, hit: real.length > 0, kinds: [...new Set(real.map((f) => f.kind))] };
    });

    const positives = rows.filter((r) => r.expect_hit);
    const negatives = rows.filter((r) => !r.expect_hit);
    const detected = positives.filter((r) => r.hit);
    const missed = positives.filter((r) => !r.hit).map((r) => r.id);
    const falsePositives = negatives.filter((r) => r.hit).map((r) => r.id);
    const recall = positives.length > 0 ? detected.length / positives.length : 1;
    const fpRate = negatives.length > 0 ? falsePositives.length / negatives.length : 0;
    const precision =
        detected.length + falsePositives.length > 0
            ? detected.length / (detected.length + falsePositives.length)
            : 1;

    it('publishes the measured rates', () => {
        const report = {
            _doc:
                'Adversarial fixture measurement of the secret detector (scanText). ' +
                'Regenerated by src/scripts/_lib/secret_detector_adversarial.test.ts on every run; ' +
                'hard floor asserted there (recall 100% / FP 0% outside known_gaps).',
            generated: new Date().toISOString().slice(0, 10),
            corpus_size: rows.length,
            positives: positives.length,
            negatives: negatives.length,
            detected: detected.length,
            missed,
            false_positives: falsePositives,
            known_gaps: KNOWN_GAPS,
            precision: +precision.toFixed(3),
            recall: +recall.toFixed(3),
            fp_rate: +fpRate.toFixed(3),
        };
        fs.mkdirSync(path.dirname(REPORT), { recursive: true });
        fs.writeFileSync(REPORT, `${JSON.stringify(report, null, 2)}\n`);
        expect(fs.existsSync(REPORT)).toBe(true);
    });

    it('recall floor: every positive outside known_gaps is detected', () => {
        const hardMisses = missed.filter((id) => !KNOWN_GAPS.includes(id));
        expect(hardMisses, `detector missed: ${hardMisses.join(', ')}`).toHaveLength(0);
    });

    it('FP floor: no negative control fires high/medium', () => {
        expect(falsePositives, `false positives: ${falsePositives.join(', ')}`).toHaveLength(0);
    });
});
