/**
 * Tests for src/scripts/build_proof.ts — the generated proof page (B4).
 *
 * Non-mutating: exercises the pure `render()` (reads the real docs/CLAIMS.md)
 * for determinism + required structure, and asserts the committed docs/proof.md
 * is in sync (the drift guard `--check` enforces the same in CI).
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { render, OUT_REL } from '../../src/scripts/build_proof.js';

const REPO_ROOT = join(fileURLToPath(import.meta.url), '..', '..', '..');

describe('build_proof — render()', () => {
    it('is deterministic (no timestamp / stable ordering)', () => {
        expect(render()).toBe(render());
    });

    it('emits the required proof structure', () => {
        const out = render();
        expect(out).toContain('# Proof — verify our claims yourself');
        expect(out).toContain('## See it run (< 60s, real output)');
        expect(out).toContain('](media/proof-demo.gif)');
        expect(out).toContain('## 1. Every public claim binds to evidence');
        expect(out).toContain('## 2. We publish honest nulls');
        expect(out).toContain('## 3. Known limits (published, witness-tested)');
        expect(out).toContain('## 4. What is checkable — us vs. the category');
        expect(out).toContain('## 5. Verify it yourself');
        expect(out).toContain('| Claim | Kind | Evidence | Resolves |');
        expect(out).toContain('| Claim | Our evidence | The category | Checkable? |');
        expect(out).toContain('task check-claims');
        expect(out).toContain('task check-skill-gaps');
        expect(out).toContain('task check-comparison');
    });

    it('carries the do-not-hand-edit generated marker', () => {
        expect(render()).toMatch(/GENERATED by src\/scripts\/build_proof\.ts/);
    });

    it('the committed docs/proof.md is in sync (drift guard)', () => {
        const committed = readFileSync(join(REPO_ROOT, OUT_REL), 'utf8');
        expect(committed).toBe(render());
    });
});
