/**
 * Tests for src/scripts/build_proof.ts — the generated proof page (B4).
 *
 * Non-mutating: exercises the pure `render()` (reads the real docs/CLAIMS.md)
 * for determinism + required structure, and asserts the committed docs/proof.md
 * is in sync (the drift guard `--check` enforces the same in CI).
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { render, OUT_REL, PREVENTED_FAILURES, renderPreventedFailures } from '../../src/scripts/build_proof.js';
import { load_ledger } from '../../src/scripts/check_claims.js';

const REPO_ROOT = join(fileURLToPath(import.meta.url), '..', '..', '..');

// `render()` costs ~54s (measured 2026-08-11): it walks the whole claims
// ledger, and this file called it five times, making it the single slowest
// test file in the suite at ~269s — 8.7x the next one, and enough on its own
// to push one vitest shard over the CI per-job ceiling.
//
// Rendering ONCE and reusing the string is sound precisely because the first
// test below asserts determinism: if `render()` ever stopped returning the
// same output, that test fails and the cache cannot mask it. The determinism
// test keeps two independent invocations — two calls IS what it measures.
// Do not "simplify" the other tests back to calling `render()` themselves.
const PROOF = render();

describe('build_proof — render()', () => {
    it('is deterministic (no timestamp / stable ordering)', () => {
        expect(render()).toBe(PROOF);
    });

    it('emits the required proof structure', () => {
        const out = PROOF;
        expect(out).toContain('# Proof — verify our claims yourself');
        expect(out).toContain('## See it run (< 60s, real output)');
        expect(out).toContain('](media/proof-demo.gif)');
        expect(out).toContain('## 1. Every public claim binds to evidence');
        expect(out).toContain('## 2. We publish honest nulls');
        expect(out).toContain('## 3. Known limits (published, witness-tested)');
        expect(out).toContain('## 4. What is checkable — us vs. the category');
        expect(out).toContain('## 5. Verify it yourself');
        expect(out).toContain('| Claim | Kind | Evidence | Resolves |');
        expect(out).toContain('| Claim | Our evidence | The category | Checkable? |');
        expect(out).toContain('task check-claims');
        expect(out).toContain('task check-skill-gaps');
        expect(out).toContain('task check-comparison');
    });

    it('carries the do-not-hand-edit generated marker', () => {
        expect(PROOF).toMatch(/GENERATED by src\/scripts\/build_proof\.ts/);
    });

    it('the committed docs/proof.md is in sync (drift guard)', () => {
        const committed = readFileSync(join(REPO_ROOT, OUT_REL), 'utf8');
        expect(committed).toBe(PROOF);
    });
});

describe('build_proof — the prevented-failure table may not outlive its evidence', () => {
    it('renders a row per declared failure mode', () => {
        const out = renderPreventedFailures(load_ledger());
        expect(out).toContain('## What this prevents');
        for (const row of PREVENTED_FAILURES) {
            expect(out).toContain(`[\`${row.backs}\`](CLAIMS.md)`);
        }
    });

    it('every declared row cites a claim that is actually backed today', () => {
        const ledger = load_ledger();
        for (const row of PREVENTED_FAILURES) {
            expect(ledger.get(row.backs)?.status, `row cites ${row.backs}`).toBe('backed');
        }
    });

    it('THROWS when a cited claim has no ledger entry — the anti-marketing gate', () => {
        // The failure this table exists to avoid: a cell whose number resolves
        // nowhere. If a claim is renamed or dropped, generation must break
        // rather than silently ship a stale row.
        const ledger = load_ledger();
        ledger.delete(PREVENTED_FAILURES[0]!.backs);
        expect(() => renderPreventedFailures(ledger)).toThrow(/no ledger entry/);
    });

    it('THROWS when a cited claim is downgraded to unbacked', () => {
        const ledger = load_ledger();
        const id = PREVENTED_FAILURES[0]!.backs;
        const entry = ledger.get(id)!;
        ledger.set(id, { ...entry, status: 'unbacked' });
        expect(() => renderPreventedFailures(ledger)).toThrow(/not 'backed'/);
    });
});
