// CLI intent tests for gen_discovery_baseline (py2ts Phase 8 / Wave 8h).
// No pytest suite exists — the tsx CLI is exercised against the real repo.
// The script WRITES `agents/notes/discovery-baseline.md`; each test snapshots
// that file, runs the CLI, and RESTORES the original (or removes it if it did
// not exist) — it never leaves the live repo mutated.
//
// NON-DETERMINISM: the `> Generated by … on <UTC timestamp>` line stamps the
// current UTC time. That single line is normalised away before the
// determinism comparison; every other line + the stdout message is
// deterministic for a given repo tree, so structural assertions (not repo
// byte-content) are used.
import * as fs from 'node:fs';
import * as path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { REPO_ROOT, runTs } from './_wave8h.js';

const DEST = path.join(REPO_ROOT, 'agents', 'notes', 'discovery-baseline.md');

let existedBefore = false;
let originalContent: string | null = null;

beforeEach(() => {
    existedBefore = fs.existsSync(DEST);
    originalContent = existedBefore ? fs.readFileSync(DEST, 'utf-8') : null;
});

afterEach(() => {
    if (existedBefore && originalContent !== null) {
        fs.mkdirSync(path.dirname(DEST), { recursive: true });
        fs.writeFileSync(DEST, originalContent, 'utf-8');
    } else if (fs.existsSync(DEST)) {
        fs.rmSync(DEST, { force: true });
    }
});

const GENERATED_RE = /^> Generated by `gen_discovery_baseline`\. Do not edit\. Stamped .*$/m;

/** Replace the single non-deterministic generated-at line. */
function normalise(md: string): string {
    return md.replace(
        GENERATED_RE,
        '> Generated by `scripts/gen_discovery_baseline.py` on <UTC>.',
    );
}

describe('gen_discovery_baseline — CLI (real repo, snapshot+restore)', () => {
    it('writes the baseline .md, deterministic apart from the timestamp line', () => {
        const first = runTs('gen_discovery_baseline', []);
        expect(first.status).toBe(0);
        const firstMd = fs.readFileSync(DEST, 'utf-8');

        // Structural shape: title header + the (masked) generated-at line.
        expect(firstMd.startsWith('# Discovery Baseline — Inventory (Phase 0.1)\n')).toBe(true);
        expect(firstMd).toMatch(GENERATED_RE);

        // A second run differs at most in the timestamp line.
        const second = runTs('gen_discovery_baseline', []);
        expect(second.status).toBe(0);
        const secondMd = fs.readFileSync(DEST, 'utf-8');
        expect(normalise(secondMd)).toBe(normalise(firstMd));
    });

    it('stdout reports the destination + line count', () => {
        const r = runTs('gen_discovery_baseline', []);
        expect(r.status).toBe(0);
        expect(r.stderr).toBe('');
        // `wrote {dest} — {n} lines`
        expect(r.stdout).toMatch(
            new RegExp(`^wrote ${DEST.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')} — \\d+ lines\\n$`),
        );
    });
});
