// Focused differential for gen_discovery_baseline (py2ts Phase 8 / Wave 8h).
// No pytest suite exists — golden parity on the real repo. The script WRITES
// `agents/notes/discovery-baseline.md`; this test snapshots that file, runs
// python3 then tsx, captures each written artefact, and RESTORES the original
// (or removes it if it did not exist) — it never leaves the live repo mutated.
//
// NON-DETERMINISM EXCLUDED: the `> Generated by … on <UTC timestamp>` line
// stamps the current UTC time. That single line is normalised away before the
// byte-comparison; every other line + the stdout line-count is deterministic.
import * as fs from 'node:fs';
import * as path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { REPO_ROOT, hasPython3, runPy, runTs } from './_wave8h.js';

const DEST = path.join(REPO_ROOT, 'agents', 'notes', 'discovery-baseline.md');

let existedBefore = false;
let originalContent: string | null = null;

beforeEach(() => {
    existedBefore = fs.existsSync(DEST);
    originalContent = existedBefore ? fs.readFileSync(DEST, 'utf-8') : null;
});

afterEach(() => {
    if (existedBefore && originalContent !== null) {
        fs.mkdirSync(path.dirname(DEST), { recursive: true });
        fs.writeFileSync(DEST, originalContent, 'utf-8');
    } else if (fs.existsSync(DEST)) {
        fs.rmSync(DEST, { force: true });
    }
});

/** Replace the single non-deterministic generated-at line. */
function normalise(md: string): string {
    return md.replace(
        /^> Generated by `scripts\/gen_discovery_baseline\.py` on .*$/m,
        '> Generated by `scripts/gen_discovery_baseline.py` on <UTC>.',
    );
}

describe('gen_discovery_baseline — golden parity (real repo, snapshot+restore)', () => {
    it.skipIf(!hasPython3())('written .md byte-identical (timestamp excluded)', () => {
        const py = runPy('gen_discovery_baseline', []);
        expect(py.status).toBe(0);
        const pyMd = fs.readFileSync(DEST, 'utf-8');

        const ts = runTs('gen_discovery_baseline', []);
        expect(ts.status).toBe(0);
        const tsMd = fs.readFileSync(DEST, 'utf-8');

        expect(normalise(tsMd)).toBe(normalise(pyMd));
    });

    it.skipIf(!hasPython3())('stdout line-count message byte-identical', () => {
        const py = runPy('gen_discovery_baseline', []);
        const ts = runTs('gen_discovery_baseline', []);
        // `wrote {dest} — {n} lines` — same dest, same deterministic line count.
        expect(ts.stdout).toBe(py.stdout);
    });
});
