// Tests for src/scripts/_lib/generated_by.ts and the tree-wide invariant it
// exists to hold — road-to-consumer-repo-reality Phase 1, step 1.4.
//
// The step's verify is literal: "grep the generated-artefact templates for a
// literal script path; zero matches, and the count is reported so a future
// addition is visible." The sweep below is that grep, and it reports its
// scanned count on the green path so the denominator is never silent.
//
// It is a TEST rather than a registered gate deliberately. A new gate-coverage
// row owes a `reportScanned` count, a `--self-test`, and trips three separate
// ratchets; the invariant here is a property of this repository's own source
// that CI already runs the suite over. A gate would buy nothing the suite does
// not already give and would cost the estate three entries.
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
    generatedBy,
    generatedByComment,
    generatedByItalic,
    generatedByQuote,
} from '../../src/scripts/_lib/generated_by.js';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

describe('generatedBy — the attribution is a command or a module name', () => {
    it('emits a stable reference', () => {
        expect(generatedBy('regenerate_index')).toBe('Generated by `regenerate_index`. Do not edit.');
    });

    it('appends a detail clause when given one', () => {
        expect(generatedBy('fold_intake', '(deterministic, no LLM.)')).toBe(
            'Generated by `fold_intake`. Do not edit. (deterministic, no LLM.)',
        );
    });

    it('REFUSES a path rather than emitting one — the defect is the emission', () => {
        expect(() => generatedBy('src/scripts/regenerate_index.ts')).toThrow(/path separator/);
        expect(() => generatedBy('scripts\\win.ts')).toThrow(/path separator/);
    });

    it('carries no timestamp — a regenerated stamp makes every run a diff', () => {
        expect(generatedBy('x')).toBe(generatedBy('x'));
        expect(generatedBy('x')).not.toMatch(/\d{4}-\d{2}-\d{2}/);
    });

    it('wraps in the three shapes emitters actually use', () => {
        expect(generatedByQuote('x')).toBe('> Generated by `x`. Do not edit.');
        expect(generatedByItalic('x')).toBe('_Generated by `x`. Do not edit._');
        expect(generatedByComment('x')).toBe('# Generated by `x`. Do not edit.');
    });
});

// ---------------------------------------------------------------------------
// The tree-wide sweep — step 1.4's verify, executed
// ---------------------------------------------------------------------------

/**
 * A generator naming itself by literal path in the output it EMITS.
 *
 * THE FIRST VERSION OF THIS PATTERN RETURNED A FALSE GREEN. It required exactly
 * `Generated by ` followed by whitespace and an optional backtick, and reported
 * "0 hits" while fifteen attributions survived in five shapes it could not see:
 * all-caps `GENERATED by`, an escaped backtick inside a template literal, a bold
 * `**Generated by:**`, a markdown link `[\`src/…\`](…)`, and an `npx tsx `
 * prefix. One of the survivors named `scripts/generate_command_flows.py`, which
 * does not exist — a live instance of the defect the sweep exists to remove.
 *
 * A sweep with no positive control cannot tell "clean" from "blind", which is
 * why one is asserted below.
 *
 * The gap between the verb and `by` allows only whitespace and bold markers, so
 * `generated FROM docs/CLAIMS.md BY src/scripts/build_proof.ts` does not match.
 * That grammar names a generator's INPUT and its tool inside a gate's own
 * provenance table; it is a reference, not an attribution emitted into a
 * generated artifact, and sweeping it would be a false positive.
 *
 * Anchored on the attribution verb so it matches an emitted line rather than a
 * docblock or an import: prose in a comment may legitimately cite a path, and
 * flagging that would be noise. What must not survive is the attribution a
 * READER of the generated file sees.
 */
const SELF_REFERENCE =
    /(?:Auto-|Re)?(?:GENERATED|[Gg]enerated)(?:_by|[\s*]{0,4}by)[^\n'"]{0,40}?((?:src\/)?scripts\/[A-Za-z0-9_/-]+\.(?:ts|py|sh|js))/g;

function walk(dir: string, out: string[] = []): string[] {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
        if (ent.name === 'node_modules' || ent.name.startsWith('.')) continue;
        const abs = path.join(dir, ent.name);
        if (ent.isDirectory()) walk(abs, out);
        else if (ent.name.endsWith('.ts') && !ent.name.endsWith('.test.ts')) out.push(abs);
    }
    return out;
}

describe('1.4 — no generated artifact hard-codes its generator path', () => {
    // POSITIVE CONTROL. Without it, any narrowing of SELF_REFERENCE still passes
    // and the sweep silently stops detecting anything — which is exactly what
    // happened to its first version.
    it('DETECTS every shape the survivors were written in', () => {
        const shapes = [
            'Generated by `src/scripts/x.ts`',
            'GENERATED by src/scripts/x.ts',
            'Auto-generated by `scripts/x.py`',
            'Regenerated by `scripts/x.py`',
            '**Generated by:** `src/scripts/x.ts`',
            'Generated by [`src/scripts/x.ts`](../x)',
            'generated by `npx tsx src/scripts/x.ts --table`',
            'generated_by: src/scripts/x.ts',
        ];
        for (const shape of shapes) {
            SELF_REFERENCE.lastIndex = 0;
            expect(SELF_REFERENCE.test(shape), shape).toBe(true);
        }
    });

    it('does NOT fire on the replacement form', () => {
        for (const ok of ['Generated by `regenerate_index`. Do not edit.', 'Generated by `task sync`. Do not edit.']) {
            SELF_REFERENCE.lastIndex = 0;
            expect(SELF_REFERENCE.test(ok), ok).toBe(false);
        }
    });

    it('finds zero literal script paths in emitted attributions, over a reported count', () => {
        const files = walk(path.join(REPO, 'src'));
        const hits: string[] = [];
        for (const abs of files) {
            const text = fs.readFileSync(abs, 'utf8');
            SELF_REFERENCE.lastIndex = 0;
            let m: RegExpExecArray | null;
            while ((m = SELF_REFERENCE.exec(text)) !== null) {
                hits.push(`${path.relative(REPO, abs)} → ${m[1] ?? ''}`);
            }
        }
        // The denominator is reported on the green path. A sweep that says only
        // "no matches" cannot be told apart from a sweep that scanned nothing.
        // eslint-disable-next-line no-console
        console.log(`generator self-reference sweep: scanned ${files.length} source file(s), ${hits.length} hit(s)`);
        expect(hits).toEqual([]);
        expect(files.length).toBeGreaterThan(200);
    });
});
