// The per-host standing-cost table generator (road-to-delivery-for-every-host 7.2).
//
// The roadmap asks for two properties, and the SECOND one is why this file
// exists: the table numbers must equal the census, AND the generator must fail
// when the census is missing. A generator tested only on its happy path would
// satisfy the first and silently render an empty table for the second — which
// reads as "this package has no standing cost", the most misleading output this
// code could produce. So every refusal path is pinned here, and the pass path is
// the smallest part of the file.
import { describe, expect, it } from 'vitest';

import {
    censusPin,
    disagreements,
    parseCensus,
    renderTable,
    type HostRow,
} from '../../src/scripts/generate_host_cost_table.js';

const CENSUS = `<!-- evidence-type: analysis -->
# Standing rule payload, per host

Pinned to commit \`abc1234def5678\`. Generated by a script.

## Per host

| Host | Surface | Shape | Bytes | chars/4 tok | Writer |
|---|---|---|---:|---:|---|
| \`claude-code\` | \`.claude/rules\` | per-rule tree | 486068 | 121517 | \`x.ts:1\` |
| \`gemini\` | \`GEMINI.md\` | single file | 2982 | 746 | \`y.ts:2\` |
| \`cowork\` | — | none | — | — | — |

Notes per host:
`;

describe('census parsing is strict, because a silently shorter table is a false claim', () => {
    it('reads every host row, including the none-surface row', () => {
        const rows = parseCensus(CENSUS);
        expect(rows.map((r) => r.host)).toStrictEqual(['claude-code', 'gemini', 'cowork']);
        expect(rows[0]?.bytes).toBe('486068');
        expect(rows[0]?.tokens).toBe('121517');
        expect(rows[2]?.surface).toBe('—');
    });

    it('strips backticks so a row compares against the tree, not against markdown', () => {
        expect(parseCensus(CENSUS)[0]?.surface).toBe('.claude/rules');
    });

    it('drops the header and separator rows rather than publishing them as hosts', () => {
        for (const r of parseCensus(CENSUS)) {
            expect(r.host).not.toBe('Host');
            expect(r.host).not.toMatch(/^-+$/);
        }
    });

    it('returns nothing when the section heading is absent — the format moved', () => {
        expect(parseCensus(CENSUS.replace('## Per host', '## Something Else'))).toStrictEqual([]);
    });

    it('returns nothing when the section is present but has no rows', () => {
        expect(parseCensus('## Per host\n\nnothing here\n')).toStrictEqual([]);
    });

    it('stops at the first non-table line after the rows, never swallowing a later table', () => {
        const two = CENSUS + '\n| Other | Table |\n|---|---|\n| a | b |\n';
        expect(parseCensus(two).map((r) => r.host)).toStrictEqual([
            'claude-code',
            'gemini',
            'cowork',
        ]);
    });
});

describe('the pin, without which the census is not evidence', () => {
    it('is read from the census header', () => {
        expect(censusPin(CENSUS)).toBe('abc1234def5678');
    });

    it('is null when the census declares none — a reader could not reproduce it', () => {
        expect(censusPin(CENSUS.replace(/Pinned to commit `[0-9a-f]+`/, 'Unpinned'))).toBeNull();
    });
});

describe('the census is cross-checked against the tree, not trusted', () => {
    const live = new Map([
        ['claude-code', { bytes: '486068', tokens: '121517' }],
        ['gemini', { bytes: '2982', tokens: '746' }],
    ]);

    it('agreement produces no findings', () => {
        const rows: HostRow[] = [
            { host: 'claude-code', surface: '.claude/rules', shape: 'per-rule tree', bytes: '486068', tokens: '121517' },
        ];
        expect(disagreements(rows, live)).toStrictEqual([]);
    });

    it('a STALE census is caught, which the roadmap own verify could not do', () => {
        // The real case, measured 2026-09-09: the committed census read 486063 B
        // while the tree read 486068 B. "Table equals the census" is satisfied by
        // a stale census; only the second reading catches it.
        const rows: HostRow[] = [
            { host: 'claude-code', surface: '.claude/rules', shape: 'per-rule tree', bytes: '486063', tokens: '121516' },
        ];
        const found = disagreements(rows, live);
        expect(found.length).toBe(1);
        expect(found[0]).toContain('census says 486063');
        expect(found[0]).toContain('the tree says 486068');
    });

    it('a host in the census but absent from the tree is a finding, not a skip', () => {
        const rows: HostRow[] = [
            { host: 'ghost-host', surface: '.ghost', shape: 'single file', bytes: '1', tokens: '1' },
        ];
        expect(disagreements(rows, live)[0]).toContain('absent from HOST_SURFACES');
    });

    it('a token-only drift is caught even when the byte count matches', () => {
        const rows: HostRow[] = [
            { host: 'gemini', surface: 'GEMINI.md', shape: 'single file', bytes: '2982', tokens: '999' },
        ];
        expect(disagreements(rows, live).length).toBe(1);
    });
});

describe('the rendered table', () => {
    it('carries the pin, so the number can be reproduced', () => {
        expect(renderTable(parseCensus(CENSUS), 'abc1234')).toContain('abc1234');
    });

    it('states the unit and refuses to imply consumption', () => {
        const t = renderTable(parseCensus(CENSUS), 'abc1234');
        expect(t).toContain('upper bound');
        expect(t).toContain('delivery, not consumption');
    });

    it('points at the per-install reading rather than leaving the two conflatable', () => {
        expect(renderTable(parseCensus(CENSUS), 'abc1234')).toContain(
            'check_preamble_payload_budget --host',
        );
    });

    it('renders the none-surface host without wrapping the dash in code ticks', () => {
        expect(renderTable(parseCensus(CENSUS), 'abc1234')).toContain('| `cowork` | — | none |');
    });

    it('is delimited by both markers, so a re-run replaces rather than appends', () => {
        const t = renderTable(parseCensus(CENSUS), 'abc1234');
        expect(t.startsWith('<!-- BEGIN generated: host-standing-cost -->')).toBe(true);
        expect(t.trimEnd().endsWith('<!-- END generated: host-standing-cost -->')).toBe(true);
    });
});

describe('the live generator against the real tree', () => {
    it('reports the contract in sync, and the census agreeing with the tree', async () => {
        // An integration check on the committed state: if the census drifts from
        // the tree, or the contract table drifts from the census, this reds. That
        // is the drift this generator exists to make visible, so it is asserted
        // here rather than left to a human noticing.
        const mod = await import('../../src/scripts/generate_host_cost_table.js');
        expect(mod.main(['--check'])).toBe(0);
    });
});
