// Tests for src/scripts/_lib/generated_by.ts and the tree-wide invariant it
// exists to hold — road-to-consumer-repo-reality Phase 1, step 1.4.
//
// The step's verify is literal: "grep the generated-artefact templates for a
// literal script path; zero matches, and the count is reported so a future
// addition is visible." The sweep below is that grep, and it reports its
// scanned count on the green path so the denominator is never silent.
//
// It is a TEST rather than a registered gate deliberately. A new gate-coverage
// row owes a `reportScanned` count, a `--self-test`, and trips three separate
// ratchets; the invariant here is a property of this repository's own source
// that CI already runs the suite over. A gate would buy nothing the suite does
// not already give and would cost the estate three entries.
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
    generatedBy,
    generatedByComment,
    generatedByItalic,
    generatedByQuote,
} from '../../src/scripts/_lib/generated_by.js';

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

describe('generatedBy — the attribution is a command or a module name', () => {
    it('emits a stable reference', () => {
        expect(generatedBy('regenerate_index')).toBe('Generated by `regenerate_index`. Do not edit.');
    });

    it('appends a detail clause when given one', () => {
        expect(generatedBy('fold_intake', '(deterministic, no LLM.)')).toBe(
            'Generated by `fold_intake`. Do not edit. (deterministic, no LLM.)',
        );
    });

    it('REFUSES a path rather than emitting one — the defect is the emission', () => {
        expect(() => generatedBy('src/scripts/regenerate_index.ts')).toThrow(/path separator/);
        expect(() => generatedBy('scripts\\win.ts')).toThrow(/path separator/);
    });

    it('carries no timestamp — a regenerated stamp makes every run a diff', () => {
        expect(generatedBy('x')).toBe(generatedBy('x'));
        expect(generatedBy('x')).not.toMatch(/\d{4}-\d{2}-\d{2}/);
    });

    it('wraps in the three shapes emitters actually use', () => {
        expect(generatedByQuote('x')).toBe('> Generated by `x`. Do not edit.');
        expect(generatedByItalic('x')).toBe('_Generated by `x`. Do not edit._');
        expect(generatedByComment('x')).toBe('# Generated by `x`. Do not edit.');
    });
});

// ---------------------------------------------------------------------------
// The tree-wide sweep — step 1.4's verify, executed
// ---------------------------------------------------------------------------

/**
 * A generator naming itself by literal path in the output it EMITS.
 *
 * Anchored on the attribution verb so it matches an emitted line rather than a
 * docblock or an import: prose in a comment may legitimately cite a path, and
 * flagging that would be noise. What must not survive is the attribution a
 * READER of the generated file sees.
 */
const SELF_REFERENCE = /(?:Auto-|Re)?[Gg]enerated by\s+`?((?:src\/)?scripts\/[A-Za-z0-9_/-]+\.(?:ts|py|sh|js))`?/g;

function walk(dir: string, out: string[] = []): string[] {
    for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
        if (ent.name === 'node_modules' || ent.name.startsWith('.')) continue;
        const abs = path.join(dir, ent.name);
        if (ent.isDirectory()) walk(abs, out);
        else if (ent.name.endsWith('.ts') && !ent.name.endsWith('.test.ts')) out.push(abs);
    }
    return out;
}

describe('1.4 — no generated artifact hard-codes its generator path', () => {
    it('finds zero literal script paths in emitted attributions, over a reported count', () => {
        const files = walk(path.join(REPO, 'src'));
        const hits: string[] = [];
        for (const abs of files) {
            const text = fs.readFileSync(abs, 'utf8');
            SELF_REFERENCE.lastIndex = 0;
            let m: RegExpExecArray | null;
            while ((m = SELF_REFERENCE.exec(text)) !== null) {
                hits.push(`${path.relative(REPO, abs)} → ${m[1] ?? ''}`);
            }
        }
        // The denominator is reported on the green path. A sweep that says only
        // "no matches" cannot be told apart from a sweep that scanned nothing.
        // eslint-disable-next-line no-console
        console.log(`generator self-reference sweep: scanned ${files.length} source file(s), ${hits.length} hit(s)`);
        expect(hits).toEqual([]);
        expect(files.length).toBeGreaterThan(200);
    });
});
