// Tests for src/scripts/generate_command_flows.ts (py2ts Phase 8 / Wave 8a).
//
// No pytest suite exists for this module. WRITER → the golden-parity layer
// asserts python3 and tsx render docs/command-flows.md byte-identically and
// that a write run leaves zero git drift vs the committed doc. A focused
// behavioural layer covers the pure `render()` output shape. Skipped without
// python3.
import { describe, expect, it } from 'vitest';

import * as gcf from '../../src/scripts/generate_command_flows.js';



describe('generate_command_flows — render() shape', () => {
    it('renders the generated header, title, and surface sections', () => {
        const md = gcf.render();
        expect(md.startsWith('<!-- GENERATED by scripts/generate_command_flows.py')).toBe(true);
        expect(md).toContain('# Command flows — the primary view');
        expect(md).toContain('## User-work flows');
        expect(md).toContain('## Platform & domain surfaces');
        // Ends with exactly one trailing newline (rstrip + "\n").
        expect(md.endsWith('\n')).toBe(true);
        expect(md.endsWith('\n\n')).toBe(false);
    });

    it('counts commands across surfaces in the summary line', () => {
        const md = gcf.render();
        expect(md).toMatch(/\*\*\d+ commands\*\* across \*\*\d+ surfaces\*\*/);
    });
});
