/**
 * Polarity fixtures for `lint_code_comments`.
 *
 * The corpus itself is NOT here. It is `COMMENT_CASES`, exported by the gate,
 * and `--self-test` enumerates the same table against the real binary. Two
 * tables over one classifier drift, and the one nobody runs locally drifts
 * first — so this file asserts the exact class set the pure classifier
 * reports, and the self-test asserts the exit code the CLI returns, over
 * identical input.
 *
 * Both directions are pinned, because a pattern gate is only as good as the
 * near-miss it stays silent on: the MUST-FIRE half is what the rule asks for,
 * and the MUST-NOT-FIRE half is the whole reason this gate can be turned on
 * in a repository whose own module docstrings are long, cite evidence and
 * quote German user speech as data.
 */
import { execFileSync } from 'node:child_process';
import * as path from 'node:path';
import { describe, expect, it } from 'vitest';

import {
    COMMENT_CASES,
    fileIsExempt,
    findingsOnAddedLines,
    isScannable,
    parseAddedLines,
    scanText,
} from '../../src/scripts/lint_code_comments.js';

describe('classifier fixture table', () => {
    it.each(COMMENT_CASES.map((c) => [c.name, c] as const))('%s', (_name, testCase) => {
        // The DISTINCT class set, not the finding count. A multi-line fixture
        // reports one finding per offending line, and `flags` declares which
        // classes fire rather than how many times — a count assertion would
        // make the table brittle against a scanner that legitimately
        // classifies a continuation line the opener already covered.
        const actual = [...new Set(scanText('f.ts', testCase.source).map((f) => f.cls))].sort();
        expect(actual).toEqual([...new Set(testCase.flags)].sort());
    });

    it('pins both polarities, so a truncated table fails here too', () => {
        const firing = COMMENT_CASES.filter((c) => c.flags.length > 0);
        const silent = COMMENT_CASES.filter((c) => c.flags.length === 0);
        expect(firing.length).toBeGreaterThanOrEqual(8);
        expect(silent.length).toBeGreaterThanOrEqual(8);
    });

    it('covers every class the gate can report', () => {
        const covered = new Set(COMMENT_CASES.flatMap((c) => c.flags));
        expect([...covered].sort()).toEqual([
            'de-comment',
            'provenance-comment',
            'report-comment',
        ]);
    });
});

describe('file-level exemption', () => {
    it('treats a generated-file header as exempt', () => {
        expect(fileIsExempt('// Generated by wrangler. DO NOT EDIT.\n')).toBe(true);
    });

    it('does not treat an ordinary header as exempt', () => {
        expect(fileIsExempt('// Token definitions for the todo surface.\n')).toBe(false);
    });
});

describe('scope', () => {
    it('scans source extensions', () => {
        for (const f of ['a.ts', 'a.tsx', 'a.css', 'a.php', 'a.py', 'a.go'])
            expect(isScannable(f)).toBe(true);
    });

    it('skips declarations, vendored and generated trees', () => {
        for (const f of ['a.d.ts', 'node_modules/x/a.ts', 'dist/a.ts', 'vendor/a.php', 'a.md'])
            expect(isScannable(f)).toBe(false);
    });
});

describe('lint_code_comments — the CLI self-test actually runs somewhere', () => {
    it('drives the real binary and reports both floors as met', () => {
        // Finding 1 of the completion review: CI runs this gate only in diff
        // mode, which exits 0 on an empty diff, so nothing exercised the
        // `--self-test` dispatch, the tmpdir/`--paths` wiring, or the exit-code
        // mapping. A regression in that half shipped green.
        let code = 0;
        let stdout = '';
        try {
            stdout = execFileSync('./scripts-run', ['src/scripts/lint_code_comments', '--self-test'], {
                cwd: path.resolve(__dirname, '..', '..'),
                encoding: 'utf-8',
                stdio: ['ignore', 'pipe', 'pipe'],
            });
        } catch (e) {
            const err = e as { status?: number; stdout?: string };
            code = err.status ?? 1;
            stdout = err.stdout ?? '';
        }
        expect(code).toBe(0);
        expect(stdout).toContain('case(s) behaved');
        expect(COMMENT_CASES.filter((c) => c.flags.length > 0).length).toBeGreaterThanOrEqual(8);
    });

    it('refuses to nest inside a self-test child', () => {
        let code = 0;
        try {
            execFileSync('./scripts-run', ['src/scripts/lint_code_comments', '--self-test'], {
                cwd: path.resolve(__dirname, '..', '..'),
                encoding: 'utf-8',
                stdio: ['ignore', 'pipe', 'pipe'],
                env: { ...process.env, GATE_SELF_TEST_CHILD: '1' },
            });
        } catch (e) {
            code = (e as { status?: number }).status ?? 1;
        }
        expect(code).toBe(2);
    });
});

// ── Diff scoping: the gate answers for the lines the diff wrote ─────────────
//
// `.github/workflows/rule-backstops.yml` describes this gate as "diff-scoped,
// so a pre-existing tree does not turn red". Selecting the FILE set from the
// diff while scanning each file whole delivered that only for files nobody
// touched: measured 2026-09-02 on PR #1813, which added no flagged comment and
// was refused on eleven legacy lines in four files it had edited for unrelated
// reasons. Both halves are pinned here — a finding on an added line survives,
// a finding on an untouched line does not, and a file outside the diff
// contributes nothing at all.
describe('diff scoping — findings are filtered to the lines the diff added', () => {
  it('reads added line numbers and counts out of --unified=0 hunk headers', () => {
    const patch = [
      'diff --git a/src/a.ts b/src/a.ts',
      '--- a/src/a.ts',
      '+++ b/src/a.ts',
      '@@ -10,0 +11,3 @@',
      '+// one',
      '+// two',
      '+// three',
      '@@ -40 +43 @@',
      '-// old',
      '+// new',
    ].join('\n');
    const map = parseAddedLines(patch);
    expect([...(map.get('src/a.ts') ?? [])].sort((x, y) => x - y)).toEqual([11, 12, 13, 43]);
  });

  it('treats a header with no count as exactly one line', () => {
    const map = parseAddedLines(['+++ b/x.ts', '@@ -4 +4 @@', '+// x'].join('\n'));
    expect([...(map.get('x.ts') ?? [])]).toEqual([4]);
  });

  it('adds nothing for a deletion, whose post-image is /dev/null', () => {
    const map = parseAddedLines(['+++ /dev/null', '@@ -1,5 +0,0 @@'].join('\n'));
    expect(map.size).toBe(0);
  });

  it('keeps a finding the diff put on an added line', () => {
    const f = [{ cls: 'de-comment', file: 'a.ts', line: 12, signal: 'x', snippet: 's' }] as const;
    expect(findingsOnAddedLines(f, new Set([12]))).toHaveLength(1);
  });

  it('drops a finding on a line the diff never touched — the #1813 case', () => {
    const f = [{ cls: 'report-comment', file: 'a.ts', line: 230, signal: 'box-rule', snippet: 's' }] as const;
    expect(findingsOnAddedLines(f, new Set([12, 13]))).toEqual([]);
  });

  it('keeps everything in an untracked file, whose every line is new', () => {
    const f = [{ cls: 'de-comment', file: 'new.ts', line: 900, signal: 'x', snippet: 's' }] as const;
    expect(findingsOnAddedLines(f, 'all')).toHaveLength(1);
  });

  it('keeps nothing for a file the diff did not touch at all', () => {
    const f = [{ cls: 'de-comment', file: 'other.ts', line: 1, signal: 'x', snippet: 's' }] as const;
    expect(findingsOnAddedLines(f, undefined)).toEqual([]);
  });
});
