/**
 * Rule → skill/guideline backlink derivation (feedback-8.11 Phase 6).
 * Council 2026-07-12: linkage is rule-side only (routed_from_rules rejected);
 * this derivation is the skill author's inbound-routes view.
 *
 * Correctness slice: target resolution (skill:/guideline:/context:/contract:/
 * path shapes), orphan-stub detection, unknown-shape honesty, and --check
 * exit semantics (report mode always 0; --check 1 iff orphans exist).
 */
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
    candidate_paths,
    extract_backlinks,
    main,
    render,
    resolve_target,
    validate_targets,
    type Backlink,
} from "../../src/scripts/rule_backlinks.js";

const FM_RULE = `---
type: auto
routes_to:
  - "skill:analysis-skill-router"
---

# Analysis Skill Routing

Body migrated to \`skill:analysis-skill-router\` (per P4).
`;

describe("extract_backlinks", () => {
    it("reads frontmatter routes_to items", () => {
        const links = extract_backlinks("analysis-skill-routing", FM_RULE);
        expect(links.some((l) => l.target === "skill:analysis-skill-router" && l.source === "frontmatter")).toBe(true);
    });

    it("reads 'Body migrated to' prose tokens (skill: and paths)", () => {
        const links = extract_backlinks(
            "autonomous-execution",
            "# X\n\nBody migrated to `contexts/execution/autonomy-mechanics.md` (per P4).\n",
        );
        expect(links).toEqual([
            { target: "contexts/execution/autonomy-mechanics.md", rule: "autonomous-execution", source: "prose" },
        ]);
    });

    it("ignores prose mentions outside migration lines", () => {
        const links = extract_backlinks("x", "# X\n\nSee `skill:laravel` for depth.\n");
        expect(links).toEqual([]);
    });
});

describe("render", () => {
    it("renders a per-target section with rule bullets and the generated header", () => {
        const m = new Map([
            ["skill:laravel", [{ target: "skill:laravel", rule: "laravel-routing", source: "prose" as const }]],
        ]);
        const out = render(m);
        expect(out).toContain("GENERATED by rule_backlinks");
        expect(out).toContain("## skill:laravel");
        expect(out).toContain("- `laravel-routing` (prose)");
    });

    it("always carries the Orphan stubs, Fan-out, and gated-future-work sections", () => {
        const out = render(new Map());
        expect(out).toContain("## Orphan stubs");
        expect(out).toContain("## Fan-out (info)");
        expect(out).toContain("## Design notes — gated future work");
        // Round-4 later-hard-gates list, verbatim.
        expect(out).toContain(
            "invalid backlinks, cyclic\nownership, kernel-budget breach, new setting without profile default,\nnew runtime-state surface without owner, stub without valid target",
        );
        expect(out).toContain("only precise, non-proxy metrics may ever hard-gate");
        expect(out).toContain("PARKED");
    });

    it("lists rules with >2 targets in the fan-out table as info", () => {
        const mk = (target: string): [string, Backlink[]] => [
            target,
            [{ target, rule: "busy-rule", source: "frontmatter" as const }],
        ];
        const m = new Map([mk("skill:laravel"), mk("skill:docker"), mk("skill:git-workflow")]);
        const out = render(m, { orphans: [], unknownShapes: [], resolvedCount: 3 });
        expect(out).toContain("max fan-out 3");
        expect(out).toContain("| `busy-rule` | 3 |");
        expect(out).toContain("NOT failures");
    });
});

describe("target resolution", () => {
    let tmpRoot: string;

    beforeEach(() => {
        tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "rule-backlinks-"));
        for (const rel of [
            "src/skills/laravel/SKILL.md",
            "docs/guidelines/agent-infra/model-recommendation.md",
            "docs/guides/cross-repo-linked-projects.md",
            "docs/contracts/persona-schema.md",
            "src/agent-src/contexts/execution/autonomy-mechanics.md",
            "src/agent-src/contexts/contracts/command-suggestion-flow.md",
        ]) {
            const p = path.join(tmpRoot, rel);
            fs.mkdirSync(path.dirname(p), { recursive: true });
            fs.writeFileSync(p, "# fixture\n");
        }
    });

    afterEach(() => {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    });

    it("resolves every known shape to its on-disk artifact (happy path)", () => {
        const cases: [string, string][] = [
            ["skill:laravel", "src/skills/laravel/SKILL.md"],
            ["guideline:agent-infra/model-recommendation", "docs/guidelines/agent-infra/model-recommendation.md"],
            ["context:execution/autonomy-mechanics", "src/agent-src/contexts/execution/autonomy-mechanics.md"],
            ["contract:persona-schema", "docs/contracts/persona-schema.md"],
            ["contract:command-suggestion-flow", "src/agent-src/contexts/contracts/command-suggestion-flow.md"],
            ["contexts/execution/autonomy-mechanics.md", "src/agent-src/contexts/execution/autonomy-mechanics.md"],
            ["docs/guides/cross-repo-linked-projects.md", "docs/guides/cross-repo-linked-projects.md"],
        ];
        for (const [target, expected] of cases) {
            const res = resolve_target(target, tmpRoot);
            expect(res, target).toEqual({ status: "resolved", path: expected });
        }
    });

    it("reports a known shape with no artifact as an orphan, with the candidates tried", () => {
        const res = resolve_target("skill:does-not-exist", tmpRoot);
        expect(res.status).toBe("orphan");
        if (res.status === "orphan") {
            expect(res.tried).toEqual([path.join("src", "skills", "does-not-exist", "SKILL.md")]);
        }
    });

    it("reports genuinely unmappable shapes as unknown-shape, never orphan", () => {
        for (const target of ["road-to-kernel-and-router.md", "foo:bar", "agents/roadmaps/x.md"]) {
            expect(resolve_target(target, tmpRoot), target).toEqual({ status: "unknown-shape" });
            expect(candidate_paths(target), target).toBeNull();
        }
    });

    it("validate_targets buckets orphans vs unknown-shape and counts resolved", () => {
        const bl = (target: string, rule: string): [string, Backlink[]] => [
            target,
            [{ target, rule, source: "frontmatter" as const }],
        ];
        const byTarget = new Map([
            bl("skill:laravel", "laravel-routing"),
            bl("skill:deleted-skill", "stale-stub"),
            bl("weird-shape-token", "odd-rule"),
        ]);
        const v = validate_targets(byTarget, tmpRoot);
        expect(v.resolvedCount).toBe(1);
        expect(v.orphans).toEqual([
            {
                target: "skill:deleted-skill",
                rules: ["stale-stub"],
                tried: [path.join("src", "skills", "deleted-skill", "SKILL.md")],
            },
        ]);
        expect(v.unknownShapes).toEqual([{ target: "weird-shape-token", rules: ["odd-rule"] }]);
        const out = render(byTarget, v);
        expect(out).toContain("## Orphan stubs");
        expect(out).toContain("`skill:deleted-skill`");
        expect(out).toContain("## Unknown-shape targets");
        expect(out).toContain("`weird-shape-token`");
    });
});

describe("--check exit semantics", () => {
    let tmpRoot: string;

    beforeEach(() => {
        tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "rule-backlinks-check-"));
        fs.mkdirSync(path.join(tmpRoot, "src", "rules"), { recursive: true });
    });

    afterEach(() => {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    });

    const writeRule = (stem: string, target: string): void => {
        fs.writeFileSync(
            path.join(tmpRoot, "src", "rules", `${stem}.md`),
            `---\ntype: auto\nroutes_to:\n  - "${target}"\n---\n\n# ${stem}\n\nBody migrated to \`${target}\`.\n`,
        );
    };

    it("report mode always exits 0 — even with orphans present", () => {
        writeRule("stale-stub", "skill:deleted-target");
        expect(main(["--quiet"], tmpRoot)).toBe(0);
        const report = fs.readFileSync(path.join(tmpRoot, "internal", "reports", "rule-backlinks.md"), "utf-8");
        expect(report).toContain("## Orphan stubs");
        expect(report).toContain("`skill:deleted-target`");
    });

    it("--check exits 1 iff orphans exist (red path)", () => {
        writeRule("stale-stub", "skill:deleted-target");
        expect(main(["--check", "--quiet"], tmpRoot)).toBe(1);
    });

    it("--check exits 0 when every target resolves", () => {
        const skillPath = path.join(tmpRoot, "src", "skills", "laravel", "SKILL.md");
        fs.mkdirSync(path.dirname(skillPath), { recursive: true });
        fs.writeFileSync(skillPath, "# fixture\n");
        writeRule("laravel-routing", "skill:laravel");
        expect(main(["--check", "--quiet"], tmpRoot)).toBe(0);
    });

    it("--check exits 0 when only unknown-shape targets exist (honesty, not failure)", () => {
        writeRule("odd-rule", "weird:unmapped-shape");
        expect(main(["--check", "--quiet"], tmpRoot)).toBe(0);
        const report = fs.readFileSync(path.join(tmpRoot, "internal", "reports", "rule-backlinks.md"), "utf-8");
        expect(report).toContain("## Unknown-shape targets");
    });
});
