/**
 * Rule → skill/guideline backlink derivation (feedback-8.11 Phase 6).
 * Council 2026-07-12: linkage is rule-side only (routed_from_rules rejected);
 * this derivation is the skill author's inbound-routes view.
 */
import { describe, expect, it } from "vitest";

import { extract_backlinks, render } from "../../src/scripts/rule_backlinks.js";

const FM_RULE = `---
type: auto
routes_to:
  - "skill:analysis-skill-router"
---

# Analysis Skill Routing

Body migrated to \`skill:analysis-skill-router\` (per P4).
`;

describe("extract_backlinks", () => {
    it("reads frontmatter routes_to items", () => {
        const links = extract_backlinks("analysis-skill-routing", FM_RULE);
        expect(links.some((l) => l.target === "skill:analysis-skill-router" && l.source === "frontmatter")).toBe(true);
    });

    it("reads 'Body migrated to' prose tokens (skill: and paths)", () => {
        const links = extract_backlinks(
            "autonomous-execution",
            "# X\n\nBody migrated to `contexts/execution/autonomy-mechanics.md` (per P4).\n",
        );
        expect(links).toEqual([
            { target: "contexts/execution/autonomy-mechanics.md", rule: "autonomous-execution", source: "prose" },
        ]);
    });

    it("ignores prose mentions outside migration lines", () => {
        const links = extract_backlinks("x", "# X\n\nSee `skill:laravel` for depth.\n");
        expect(links).toEqual([]);
    });
});

describe("render", () => {
    it("renders a per-target section with rule bullets and the generated header", () => {
        const m = new Map([
            ["skill:laravel", [{ target: "skill:laravel", rule: "laravel-routing", source: "prose" as const }]],
        ]);
        const out = render(m);
        expect(out).toContain("GENERATED by src/scripts/rule_backlinks.ts");
        expect(out).toContain("## skill:laravel");
        expect(out).toContain("- `laravel-routing` (prose)");
    });
});
